#!/usr/bin/env python -tt
# -*- coding: utf-8 -*-

################################################################################
# Auto-generated test for: TC-004 - Smoke: End-to-End Order Placement
# Generated by: AI-Powered Agentic Test Automation System
# Generated at: 2026-04-14T14:23:01.425365
################################################################################

from __future__ import unicode_literals, absolute_import

import logging
import pytest
from datetime import datetime

from shopease_framework.base.base_test_case import ShopEaseBaseTestCase, Parameter
from shopease_framework.base.utils import TestUtils
from shopease_framework.tasks.cart_task import CartTask
from shopease_framework.workflows.checkout_flow import CheckoutFlow
from shopease_framework.tasks.notification_task import NotificationTask
from shopease_framework.tasks.order_task import OrderTask
from shopease_framework.helpers.order_config import OrderConfig
from shopease_framework.tasks.payment_task import PaymentTask
from shopease_framework.tasks.product_task import ProductTask
from shopease_framework.tasks.user_task import UserTask

LOGGER = logging.getLogger(__name__)


@pytest.mark.Smoke
class TestTC_004(ShopEaseBaseTestCase):
    """
    Smoke: End-to-End Order Placement

    Description:
        Validate the complete order placement flow from cart creation through payment processing and order confirmation on the ShopEasy platform.

    Precondition:
        ShopEasy API server is running. A registered customer account exists with verified email. At least 3 products with available stock exist. Payment gateway sandbox is configured.

    Pre-Test Steps:
        1. Load test parameters and validate testbed.
        2. Validate ShopEasy API connectivity.
        3. Validate product catalog availability.
        4. Validate order processing system.
    Run Steps:
        1. Send a POST request to /api/carts with the authenticated customer's user_id to create a new shopping
        2. Send two POST requests to /api/carts/{cart_id}/items to add two different products: Product A (quant
        3. Send a POST request to /api/carts/{cart_id}/discount with the code 'SAVE10' to apply a 10% discount 
        4. Send a POST request to /api/orders/checkout with the cart_id, shipping address, and payment method (
        5. Send a GET request to /api/orders/{order_id} to retrieve the full order details. Verify all line ite
        6. Send a GET request to /api/notifications?user_id={user_id}&type=order_confirmation to check that an 
    Post-Test:
        Revert any settings changed during the test.
    """

    _skip_pre_testcase_dump_check = True

    name = "Smoke : Smoke: End-to-End Order Placement"
    TESTCASE_ID = "TC-004"

    def __init__(self):
        super(TestTC_004, self).__init__()
        self._parameters = [
            Parameter(name="product_category", param_type="string", default="Electronics",
                      help="Default product category for test operations"),
            Parameter(name="customer_id", param_type="string", default="CUST-001",
                      help="Customer ID for order operations"),
            Parameter(name="test_email", param_type="string", default="testuser@example.com",
                      help="Test user email address"),
        ]
        self._product_id = None
        self._product_ids = []
        self._order_id = None
        self._order_ids = []
        self._cart_id = None
        self._user_id = None
        self._transaction_id = None
        self._rule_created = False

    def pre_testcase(self, testbed_obj):
        self.__dict__.update(self.params)
        ShopEaseBaseTestCase.pre_testcase(self, testbed_obj)

        LOGGER.info("Pre-Req: Validate product catalog availability")
        products = self.get_products_from_testbed(testbed_obj, product_count=1)
        LOGGER.info("Pass: Product catalog validated")

        LOGGER.info("Pre-Req: Validate order system readiness")
        LOGGER.info("Pass: Order system is ready")


    def run_test(self):
        self._step_count = 0

        # --- Step 1 ---
        LOGGER.info(f"Step {self.step_count}: Send a POST request to /api/carts with the authenticated customer's user_id to create a new shopping")
        cart_resp = CartTask.create_cart(system, self.customer_id)
        TestUtils.test_assert_true(cart_resp.get("result"), "Cart creation should succeed")
        self._cart_id = cart_resp["cart_id"]
        LOGGER.info("Cart created: %s", self._cart_id)

        # --- Step 2 ---
        LOGGER.info(f"Step {self.step_count}: Send two POST requests to /api/carts/{{cart_id}}/items to add two different products: Product A (quant")
        product_data = DataGenerator.random_product(category=self.product_category)
        create_resp = ProductTask.create_product(system, product_data)
        TestUtils.test_assert_true(create_resp.get("result"), "Product creation should succeed")
        self._product_id = create_resp["product_id"]
        self._product_ids.append(self._product_id)
        LOGGER.info("Product created: ID=%s", self._product_id)

        # --- Step 3 ---
        LOGGER.info(f"Step {self.step_count}: Send a POST request to /api/carts/{{cart_id}}/discount with the code 'SAVE10' to apply a 10% discount ")
        cart_resp = CartTask.create_cart(system, self.customer_id)
        TestUtils.test_assert_true(cart_resp.get("result"), "Cart creation should succeed")
        self._cart_id = cart_resp["cart_id"]
        LOGGER.info("Cart created: %s", self._cart_id)

        # --- Step 4 ---
        LOGGER.info(f"Step {self.step_count}: Send a POST request to /api/orders/checkout with the cart_id, shipping address, and payment method (")
        cart_resp = CartTask.create_cart(system, self.customer_id)
        TestUtils.test_assert_true(cart_resp.get("result"), "Cart creation should succeed")
        self._cart_id = cart_resp["cart_id"]
        LOGGER.info("Cart created: %s", self._cart_id)

        # --- Step 5 ---
        LOGGER.info(f"Step {self.step_count}: Send a GET request to /api/orders/{{order_id}} to retrieve the full order details. Verify all line ite")
        order_status = OrderTask.get_order_status(system, self._order_id)
        TestUtils.test_assert_true(order_status is not None, "Order status should be retrievable")
        LOGGER.info("Order %s status: %s", self._order_id, order_status.get("status"))

        # --- Step 6 ---
        LOGGER.info(f"Step {self.step_count}: Send a GET request to /api/notifications?user_id={{user_id}}&type=order_confirmation to check that an ")
        order_status = OrderTask.get_order_status(system, self._order_id)
        TestUtils.test_assert_true(order_status is not None, "Order status should be retrievable")
        LOGGER.info("Order %s status: %s", self._order_id, order_status.get("status"))


    def post_testcase(self):
        self._step_count = 0

        if self._rule_created:
            try:
                NotificationTask.delete_notification_rules(system)
            except Exception as err:
                LOGGER.warning("Failed to delete rules: %s", err)

        if self._cart_id:
            try:
                CartTask.clear_cart(system, self._cart_id)
            except Exception as err:
                LOGGER.warning("Failed to clear cart: %s", err)

        if self._user_id:
            try:
                UserTask.delete_user(system, self._user_id)
            except Exception as err:
                LOGGER.warning("Failed to delete user: %s", err)

