#!/usr/bin/env python -tt
# -*- coding: utf-8 -*-

################################################################################
# Auto-generated test for: TC-010 - Comprehensive: Notification Rules and Alerts
# Generated by: AI-Powered Agentic Test Automation System
# Generated at: 2026-04-14T14:23:01.455085
################################################################################

from __future__ import unicode_literals, absolute_import

import logging
import pytest
from datetime import datetime

from shopease_framework.base.base_test_case import ShopEaseBaseTestCase, Parameter
from shopease_framework.base.utils import TestUtils
from shopease_framework.tasks.notification_task import NotificationTask
from shopease_framework.tasks.order_task import OrderTask
from shopease_framework.helpers.order_config import OrderConfig
from shopease_framework.tasks.product_task import ProductTask

LOGGER = logging.getLogger(__name__)


@pytest.mark.Comprehensive
class TestTC_010(ShopEaseBaseTestCase):
    """
    Comprehensive: Notification Rules and Alerts

    Description:
        Test the notification rule engine including rule creation, event-driven triggering, rule modification, and cleanup on the ShopEasy platform.

    Precondition:
        ShopEasy API server is running. Admin credentials are available. Notification service is enabled. At least one webhook endpoint is configured.

    Pre-Test Steps:
        1. Load test parameters and validate testbed.
        2. Validate ShopEasy API connectivity.
        3. Validate order processing system.
    Run Steps:
        1. Send a POST request to /api/notifications/rules with a rule definition: event_type 'order.placed', c
        2. Trigger the notification rule by sending a POST request to /api/orders to create a test order with m
        3. Send a GET request to /api/notifications/log?rule_id={rule_id}&limit=5 to verify the notification wa
        4. Send a PUT request to /api/notifications/rules/{rule_id} to modify the rule. Change severity from 'i
        5. Send a DELETE request to /api/notifications/rules/{rule_id} to remove the test notification rule. Ve
    Post-Test:
        Revert any settings changed during the test.
    """

    _skip_pre_testcase_dump_check = True

    name = "Comprehensive : Comprehensive: Notification Rules and Alerts"
    TESTCASE_ID = "TC-010"

    def __init__(self):
        super(TestTC_010, self).__init__()
        self._parameters = [
            Parameter(name="customer_id", param_type="string", default="CUST-001",
                      help="Customer ID for order operations"),
        ]
        self._product_id = None
        self._product_ids = []
        self._order_id = None
        self._order_ids = []
        self._rule_created = False

    def pre_testcase(self, testbed_obj):
        self.__dict__.update(self.params)
        ShopEaseBaseTestCase.pre_testcase(self, testbed_obj)

        LOGGER.info("Pre-Req: Validate order system readiness")
        LOGGER.info("Pass: Order system is ready")


    def run_test(self):
        self._step_count = 0

        # --- Step 1 ---
        LOGGER.info(f"Step {self.step_count}: Send a POST request to /api/notifications/rules with a rule definition: event_type 'order.placed', c")
        config = OrderConfig("standard")
        config.add_item("P-101", quantity=2, price=29.99)
        config.add_item("P-102", quantity=1, price=49.99)
        config.set_payment("credit_card")
        order_resp = OrderTask.create_order(system, config.generate_order_payload())
        TestUtils.test_assert_true(order_resp.get("result"), "Order creation should succeed")
        self._order_id = order_resp["order_id"]
        LOGGER.info("Order created: %s", self._order_id)

        # --- Step 2 ---
        LOGGER.info(f"Step {self.step_count}: Trigger the notification rule by sending a POST request to /api/orders to create a test order with m")
        config = OrderConfig("standard")
        config.add_item("P-101", quantity=2, price=29.99)
        config.add_item("P-102", quantity=1, price=49.99)
        config.set_payment("credit_card")
        order_resp = OrderTask.create_order(system, config.generate_order_payload())
        TestUtils.test_assert_true(order_resp.get("result"), "Order creation should succeed")
        self._order_id = order_resp["order_id"]
        LOGGER.info("Order created: %s", self._order_id)

        # --- Step 3 ---
        LOGGER.info(f"Step {self.step_count}: Send a GET request to /api/notifications/log?rule_id={{rule_id}}&limit=5 to verify the notification wa")
        notif_sent = NotificationTask.verify_notification_sent(system, "order.placed")
        TestUtils.test_assert_true(notif_sent, "Notification should be sent")
        LOGGER.info("Notification delivery verified")

        # --- Step 4 ---
        LOGGER.info(f"Step {self.step_count}: Send a PUT request to /api/notifications/rules/{{rule_id}} to modify the rule. Change severity from 'i")
        rules = NotificationTask.get_notification_rules(system)
        TestUtils.test_assert_true(len(rules) > 0, "Should have notification rules")
        LOGGER.info("Notification rules: %d active", len(rules))

        # --- Step 5 ---
        LOGGER.info(f"Step {self.step_count}: Send a DELETE request to /api/notifications/rules/{{rule_id}} to remove the test notification rule. Ve")
        del_result = NotificationTask.delete_notification_rules(system)
        TestUtils.test_assert_true(del_result, "Rule deletion should succeed")
        self._rule_created = False
        LOGGER.info("Notification rules deleted")


    def post_testcase(self):
        self._step_count = 0

        if self._rule_created:
            try:
                NotificationTask.delete_notification_rules(system)
            except Exception as err:
                LOGGER.warning("Failed to delete rules: %s", err)

