#!/usr/bin/env python -tt
# -*- coding: utf-8 -*-

################################################################################
# Auto-generated test for: TC-008 - Comprehensive: Inventory Sync and Stock Management
# Generated by: AI-Powered Agentic Test Automation System
# Generated at: 2026-04-14T14:23:01.446446
################################################################################

from __future__ import unicode_literals, absolute_import

import logging
import pytest
from datetime import datetime

from shopease_framework.base.base_test_case import ShopEaseBaseTestCase, Parameter
from shopease_framework.base.utils import TestUtils
from shopease_framework.workflows.catalog_sync import CatalogSync
from shopease_framework.tasks.inventory_task import InventoryTask
from shopease_framework.helpers.job_helper import JobHelper
from shopease_framework.tasks.notification_task import NotificationTask
from shopease_framework.tasks.order_task import OrderTask
from shopease_framework.helpers.order_config import OrderConfig
from shopease_framework.tasks.product_task import ProductTask

LOGGER = logging.getLogger(__name__)


@pytest.mark.Comprehensive
class TestTC_008(ShopEaseBaseTestCase):
    """
    Comprehensive: Inventory Sync and Stock Management

    Description:
        Test inventory management operations including stock checks, quantity adjustments, warehouse synchronization, and low-stock alert triggers on the ShopEasy platform.

    Precondition:
        ShopEasy API server is running. Warehouse management system (WMS) is connected in sandbox mode. Product P-201 exists with initial stock quantity of 50 units. Low stock alert threshold is set to 10 units.

    Pre-Test Steps:
        1. Load test parameters and validate testbed.
        2. Validate ShopEasy API connectivity.
        3. Validate product catalog availability.
        4. Validate order processing system.
    Run Steps:
        1. Send a GET request to /api/inventory/P-201 to check the current stock level for product P-201. Recor
        2. Send a POST request to /api/inventory/P-201/adjust with adjustment_type 'add', quantity 25, and reas
        3. Send a GET request to /api/inventory/P-201 to verify the stock quantity was updated after the adjust
        4. Send a POST request to /api/inventory/sync with warehouse_id and a list of product IDs including P-2
        5. Poll the GET endpoint /api/inventory/sync/{sync_job_id} every 2 seconds for up to 30 seconds to wait
        6. Send a POST request to /api/inventory/P-201/adjust with adjustment_type 'subtract', quantity 68, and
    Post-Test:
        Revert any settings changed during the test.
    """

    _skip_pre_testcase_dump_check = True

    name = "Comprehensive : Comprehensive: Inventory Sync and Stock Management"
    TESTCASE_ID = "TC-008"

    def __init__(self):
        super(TestTC_008, self).__init__()
        self._parameters = [
            Parameter(name="product_category", param_type="string", default="Electronics",
                      help="Default product category for test operations"),
            Parameter(name="customer_id", param_type="string", default="CUST-001",
                      help="Customer ID for order operations"),
            Parameter(name="warehouse_id", param_type="string", default="WH-001",
                      help="Warehouse ID for inventory operations"),
        ]
        self._product_id = None
        self._product_ids = []
        self._order_id = None
        self._order_ids = []

    def pre_testcase(self, testbed_obj):
        self.__dict__.update(self.params)
        ShopEaseBaseTestCase.pre_testcase(self, testbed_obj)

        LOGGER.info("Pre-Req: Validate product catalog availability")
        products = self.get_products_from_testbed(testbed_obj, product_count=1)
        LOGGER.info("Pass: Product catalog validated")

        LOGGER.info("Pre-Req: Validate order system readiness")
        LOGGER.info("Pass: Order system is ready")


    def run_test(self):
        self._step_count = 0

        # --- Step 1 ---
        LOGGER.info(f"Step {self.step_count}: Send a GET request to /api/inventory/P-201 to check the current stock level for product P-201. Recor")
        cart_details = CartTask.get_cart_details(system, self._cart_id)
        LOGGER.info("Cart updated: %d items", len(cart_details.get("items", [])))

        # --- Step 2 ---
        LOGGER.info(f"Step {self.step_count}: Send a POST request to /api/inventory/P-201/adjust with adjustment_type 'add', quantity 25, and reas")
        cart_details = CartTask.get_cart_details(system, self._cart_id)
        LOGGER.info("Cart updated: %d items", len(cart_details.get("items", [])))

        # --- Step 3 ---
        LOGGER.info(f"Step {self.step_count}: Send a GET request to /api/inventory/P-201 to verify the stock quantity was updated after the adjust")
        cart_details = CartTask.get_cart_details(system, self._cart_id)
        LOGGER.info("Cart updated: %d items", len(cart_details.get("items", [])))

        # --- Step 4 ---
        LOGGER.info(f"Step {self.step_count}: Send a POST request to /api/inventory/sync with warehouse_id and a list of product IDs including P-2")
        product_data = DataGenerator.random_product(category=self.product_category)
        create_resp = ProductTask.create_product(system, product_data)
        TestUtils.test_assert_true(create_resp.get("result"), "Product creation should succeed")
        self._product_id = create_resp["product_id"]
        self._product_ids.append(self._product_id)
        LOGGER.info("Product created: ID=%s", self._product_id)

        # --- Step 5 ---
        LOGGER.info(f"Step {self.step_count}: Poll the GET endpoint /api/inventory/sync/{{sync_job_id}} every 2 seconds for up to 30 seconds to wait")
        inventory = InventoryTask.check_inventory(system, "P-201")
        TestUtils.test_assert_equals("in_stock", inventory.get("status"), "Product should be in stock")
        LOGGER.info("Inventory: %d units", inventory.get("quantity", 0))

        # --- Step 6 ---
        LOGGER.info(f"Step {self.step_count}: Send a POST request to /api/inventory/P-201/adjust with adjustment_type 'subtract', quantity 68, and")
        cart_details = CartTask.get_cart_details(system, self._cart_id)
        LOGGER.info("Cart updated: %d items", len(cart_details.get("items", [])))


    def post_testcase(self):
        self._step_count = 0

        LOGGER.info("Post-test cleanup complete.")

