#!/usr/bin/env python -tt
# -*- coding: utf-8 -*-

################################################################################
# Auto-generated test for: TC-003 - Regression: Category Management
# Generated by: AI-Powered Agentic Test Automation System
# Generated at: 2026-04-20T22:46:41.996526
################################################################################

from __future__ import unicode_literals, absolute_import

import logging
import pytest
from datetime import datetime

from shopease_framework.base.base_test_case import ShopEaseBaseTestCase, Parameter
from shopease_framework.base.utils import TestUtils
from shopease_framework.tasks.cart_task import CartTask
from shopease_framework.tasks.category_task import CategoryTask
from shopease_framework.tasks.order_task import OrderTask
from shopease_framework.helpers.order_config import OrderConfig
from shopease_framework.tasks.product_task import ProductTask

LOGGER = logging.getLogger(__name__)


@pytest.mark.Regression
class TestTC_003(ShopEaseBaseTestCase):
    """
    Regression: Category Management

    Description:
        Test the full lifecycle of product category management including creation, product association, renaming, and deletion on the ShopEasy platform.

    Precondition:
        ShopEasy API server is running. Admin user is authenticated. At least 5 uncategorized products exist in the system.

    Pre-Test Steps:
        1. Load test parameters and validate testbed.
        2. Validate ShopEasy API connectivity.
        3. Validate product catalog availability.
        4. Validate order processing system.
    Run Steps:
        1. Send a POST request to /api/categories with a JSON body containing name 'Summer Collection', descrip
        2. Send a POST request to /api/categories/{category_id}/products with a JSON body containing an array o
        3. Send a GET request to /api/categories/{category_id} to retrieve the category details and verify the 
        4. Send a PUT request to /api/categories/{category_id} with an updated name 'Summer Deals 2025' and a n
        5. Send a DELETE request to /api/categories/{category_id} with the query parameter reassign_to=uncatego
    Post-Test:
        Revert any settings changed during the test.
    """

    _skip_pre_testcase_dump_check = True

    name = "Regression : Regression: Category Management"
    TESTCASE_ID = "TC-003"

    def __init__(self):
        super(TestTC_003, self).__init__()
        self._parameters = [
            Parameter(name="product_category", param_type="string", default="Electronics",
                      help="Default product category for test operations"),
            Parameter(name="customer_id", param_type="string", default="CUST-001",
                      help="Customer ID for order operations"),
        ]
        self._product_id = None
        self._product_ids = []
        self._category_id = None
        self._order_id = None
        self._order_ids = []

    def pre_testcase(self, testbed_obj):
        self.__dict__.update(self.params)
        ShopEaseBaseTestCase.pre_testcase(self, testbed_obj)

        LOGGER.info("Pre-Req: Validate product catalog availability")
        products = self.get_products_from_testbed(testbed_obj, product_count=1)
        LOGGER.info("Pass: Product catalog validated")

        LOGGER.info("Pre-Req: Validate order system readiness")
        LOGGER.info("Pass: Order system is ready")


    def run_test(self):
        self._step_count = 0

        # --- Step 1 ---
        LOGGER.info(f"Step {self.step_count}: Send a POST request to /api/categories with a JSON body containing name 'Summer Collection', descrip")
        product_data = DataGenerator.random_product(category=self.product_category)
        create_resp = ProductTask.create_product(system, product_data)
        TestUtils.test_assert_true(create_resp.get("result"), "Product creation should succeed")
        self._product_id = create_resp["product_id"]
        self._product_ids.append(self._product_id)
        LOGGER.info("Product created: ID=%s", self._product_id)

        # --- Step 2 ---
        LOGGER.info(f"Step {self.step_count}: Send a POST request to /api/categories/{{category_id}}/products with a JSON body containing an array o")
        product_data = DataGenerator.random_product(category=self.product_category)
        create_resp = ProductTask.create_product(system, product_data)
        TestUtils.test_assert_true(create_resp.get("result"), "Product creation should succeed")
        self._product_id = create_resp["product_id"]
        self._product_ids.append(self._product_id)
        LOGGER.info("Product created: ID=%s", self._product_id)

        # --- Step 3 ---
        LOGGER.info(f"Step {self.step_count}: Send a GET request to /api/categories/{{category_id}} to retrieve the category details and verify the ")
        details = ProductTask.get_product_details(system, self._product_id)
        TestUtils.test_assert_true(details is not None, "Product details should be retrievable")
        LOGGER.info("Product %s verified: %s", self._product_id, details.get("name"))

        # --- Step 4 ---
        LOGGER.info(f"Step {self.step_count}: Send a PUT request to /api/categories/{{category_id}} with an updated name 'Summer Deals 2025' and a n")
        update_data = {"price": 69.99, "promo_tag": "Summer Sale"}
        update_resp = ProductTask.update_product(system, self._product_id, update_data)
        TestUtils.test_assert_true(update_resp.get("result"), "Product update should succeed")
        LOGGER.info("Product %s updated", self._product_id)

        # --- Step 5 ---
        LOGGER.info(f"Step {self.step_count}: Send a DELETE request to /api/categories/{{category_id}} with the query parameter reassign_to=uncatego")
        results = ProductTask.search_products(system, category=self.product_category)
        TestUtils.test_assert_true(len(results) > 0, "Category search should return results")
        LOGGER.info("Category filter returned %d products", len(results))


    def post_testcase(self):
        self._step_count = 0

        if self._category_id:
            try:
                LOGGER.info("Post-test: Deleting category %s", self._category_id)
                CategoryTask.delete_categories(system, category_id=self._category_id)
            except Exception as err:
                LOGGER.warning("Failed to delete category: %s", err)

