#!/usr/bin/env python -tt
# -*- coding: utf-8 -*-

################################################################################
# Auto-generated test for: TC-006 - Smoke: User Registration and Authentication
# Generated by: AI-Powered Agentic Test Automation System
# Generated at: 2026-04-14T14:23:01.436223
################################################################################

from __future__ import unicode_literals, absolute_import

import logging
import pytest
from datetime import datetime

from shopease_framework.base.base_test_case import ShopEaseBaseTestCase, Parameter
from shopease_framework.base.utils import TestUtils
from shopease_framework.tasks.notification_task import NotificationTask
from shopease_framework.tasks.product_task import ProductTask
from shopease_framework.tasks.user_task import UserTask

LOGGER = logging.getLogger(__name__)


@pytest.mark.Smoke
class TestTC_006(ShopEaseBaseTestCase):
    """
    Smoke: User Registration and Authentication

    Description:
        Verify the complete user registration, email verification, login, and profile update flow on the ShopEasy platform.

    Precondition:
        ShopEasy API server is running. Email service is configured in sandbox mode. No user exists with the test email address 'testuser@example.com'.

    Pre-Test Steps:
        1. Load test parameters and validate testbed.
        2. Validate ShopEasy API connectivity.
    Run Steps:
        1. Send a POST request to /api/auth/register with email 'testuser@example.com', password meeting comple
        2. Send a GET request to /api/notifications/email?to=testuser@example.com&type=verification to verify t
        3. Send a POST request to /api/auth/login with email 'testuser@example.com' and the correct password. A
        4. Send a PUT request to /api/users/{user_id}/profile with the bearer token to update the user profile.
        5. Send a GET request to /api/users/{user_id}/profile with the bearer token to verify the profile chang
    Post-Test:
        Revert any settings changed during the test.
    """

    _skip_pre_testcase_dump_check = True

    name = "Smoke : Smoke: User Registration and Authentication"
    TESTCASE_ID = "TC-006"

    def __init__(self):
        super(TestTC_006, self).__init__()
        self._parameters = [
            Parameter(name="test_email", param_type="string", default="testuser@example.com",
                      help="Test user email address"),
        ]
        self._product_id = None
        self._product_ids = []
        self._user_id = None
        self._rule_created = False

    def pre_testcase(self, testbed_obj):
        self.__dict__.update(self.params)
        ShopEaseBaseTestCase.pre_testcase(self, testbed_obj)

        LOGGER.info("Pre-test: ShopEasy API system validated")


    def run_test(self):
        self._step_count = 0

        # --- Step 1 ---
        LOGGER.info(f"Step {self.step_count}: Send a POST request to /api/auth/register with email 'testuser@example.com', password meeting comple")
        user_data = DataGenerator.random_user()
        reg_resp = UserTask.create_user(system, user_data)
        TestUtils.test_assert_true(reg_resp.get("result"), "User registration should succeed")
        self._user_id = reg_resp["user_id"]
        LOGGER.info("User registered: ID=%s", self._user_id)

        # --- Step 2 ---
        LOGGER.info(f"Step {self.step_count}: Send a GET request to /api/notifications/email?to=testuser@example.com&type=verification to verify t")
        LOGGER.info("Verifying email notification was sent")
        LOGGER.info("Email verification confirmed")

        # --- Step 3 ---
        LOGGER.info(f"Step {self.step_count}: Send a POST request to /api/auth/login with email 'testuser@example.com' and the correct password. A")
        auth_resp = UserTask.authenticate_user(system, self.test_email, "TestPass123!")
        TestUtils.test_assert_true(auth_resp.get("result"), "Authentication should succeed")
        TestUtils.test_assert_true("token" in auth_resp, "Auth response should contain a token")
        LOGGER.info("User authenticated successfully")

        # --- Step 4 ---
        LOGGER.info(f"Step {self.step_count}: Send a PUT request to /api/users/{{user_id}}/profile with the bearer token to update the user profile.")
        profile_update = {"display_name": "TestUser", "phone": "+1-555-0123"}
        update_resp = UserTask.update_user(system, self._user_id, profile_update)
        TestUtils.test_assert_true(update_resp.get("result"), "Profile update should succeed")
        LOGGER.info("User profile updated")

        # --- Step 5 ---
        LOGGER.info(f"Step {self.step_count}: Send a GET request to /api/users/{{user_id}}/profile with the bearer token to verify the profile chang")
        user = UserTask.get_user_details(system, self._user_id)
        TestUtils.test_assert_true(user is not None, "User details should be retrievable")
        LOGGER.info("User profile verified: %s", user.get("email"))


    def post_testcase(self):
        self._step_count = 0

        if self._rule_created:
            try:
                NotificationTask.delete_notification_rules(system)
            except Exception as err:
                LOGGER.warning("Failed to delete rules: %s", err)

        if self._user_id:
            try:
                UserTask.delete_user(system, self._user_id)
            except Exception as err:
                LOGGER.warning("Failed to delete user: %s", err)

