#!/usr/bin/env python
# -*- coding: utf-8 -*-

################################################################################
# Auto-generated test for: TC-011 - Smoke: Create and Verify Product - Scale Variant 11
# Generated by: AI-Powered Agentic Test Automation System (Standalone Demo)
# Generated at: 2026-05-02T13:05:59.128384
################################################################################

import logging
import pytest
from datetime import datetime

# Standalone framework imports (NO Atlas dependencies)
import sys
import os
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from standalone_framework import BaseTestCase, MockAPIClient, assert_equals, assert_true, assert_contains

LOGGER = logging.getLogger(__name__)


@pytest.mark.Smoke
class TestTC_011(BaseTestCase):
    """
    Smoke: Create and Verify Product - Scale Variant 11

    Description:
        Scalable demo variant generated from TC-001. Verify that a new product can be created in the ShopEasy platform with all required attributes and is visible in the product catalog.

    Precondition:
        ShopEasy API server is running and accessible. Valid admin credentials are available.

    Test Steps:
        1. Send a POST request to /api/products with a JSON body containing name 'Wireless Bluetooth Headphones
        2. Send a GET request to /api/products/{product_id} using the product ID returned from the creation ste
        3. Send a GET request to /api/catalog?category=Electronics to retrieve the full product catalog filtere
        4. Send a PUT request to /api/products/{product_id} with an updated price of 69.99 and a new promotiona
        5. Send a GET request to /api/products/{product_id} again to verify the price update persisted. Compare
    """

    def setup_method(self):
        """Setup method called before each test."""
        # Initialize base attributes
        self.test_data = {}
        self.step_count = 0
        self.logger = logging.getLogger(self.__class__.__name__)
        # Initialize test-specific attributes
        self.api_client = MockAPIClient()
        self.test_data["product_category"] = "Electronics"
        self.test_data["test_email"] = "testuser@example.com"
        self.test_data["warehouse_id"] = "WH-001"
        self._product_id = None
        self._product_ids = []
        self._category_id = None

    def test_tc_011(self):
        """Test case: Smoke: Create and Verify Product - Scale Variant 11"""
        # --- Step 1 ---
        self.log_step("Send a POST request to /api/products with a JSON body containing name 'Wireless Bluetooth Headphones")
        product_data = {
            "name": "Wireless Bluetooth Headphones",
            "price": 79.99,
            "category": self.test_data["product_category"],
            "sku": "WBH-1001"
        }
        response = self.api_client.create_product(product_data)
        assert_equals(201, response["status_code"], "Product creation should return 201")
        self._product_id = response["product"]["id"]
        LOGGER.info(f"Product created with ID: {self._product_id}")

        # --- Step 2 ---
        self.log_step("Send a GET request to /api/products/{product_id} using the product ID returned from the creation ste")
        response = self.api_client.get_product(self._product_id)
        assert_equals(200, response["status_code"], "Product retrieval should return 200")
        product = response["product"]
        LOGGER.info(f"Product verified: {product['name']}")

        # --- Step 3 ---
        self.log_step("Send a GET request to /api/catalog?category=Electronics to retrieve the full product catalog filtere")
        response = self.api_client.search_products(category=self.test_data["product_category"])
        assert_equals(200, response["status_code"], "Search should return 200")
        assert_true(len(response["products"]) > 0, "Search should return results")
        LOGGER.info(f"Found {len(response['products'])} products in category")

        # --- Step 4 ---
        self.log_step("Send a PUT request to /api/products/{product_id} with an updated price of 69.99 and a new promotiona")
        update_data = {"price": 69.99, "promo_tag": "Summer Sale"}
        response = self.api_client.update_product(self._product_id, update_data)
        assert_equals(200, response["status_code"], "Product update should return 200")
        LOGGER.info("Product updated successfully")

        # --- Step 5 ---
        self.log_step("Send a GET request to /api/products/{product_id} again to verify the price update persisted. Compare")
        response = self.api_client.get_product(self._product_id)
        assert_equals(200, response["status_code"], "Product retrieval should return 200")
        product = response["product"]
        LOGGER.info(f"Product verified: {product['name']}")


