#!/usr/bin/env python -tt
# -*- coding: utf-8 -*-

################################################################################
# Auto-generated test for: TC-002 - Regression: Product Search and Filtering
# Generated by: AI-Powered Agentic Test Automation System
# Generated at: 2026-04-15T15:24:20.140283
################################################################################

from __future__ import unicode_literals, absolute_import

import logging
import pytest
from datetime import datetime

from shopease_framework.base.base_test_case import ShopEaseBaseTestCase, Parameter
from shopease_framework.base.utils import TestUtils
from shopease_framework.tasks.category_task import CategoryTask
from shopease_framework.tasks.order_task import OrderTask
from shopease_framework.helpers.order_config import OrderConfig
from shopease_framework.tasks.product_task import ProductTask

LOGGER = logging.getLogger(__name__)


@pytest.mark.Regression
class TestTC_002(ShopEaseBaseTestCase):
    """
    Regression: Product Search and Filtering

    Description:
        Validate the product search and filtering functionality of the ShopEasy platform, ensuring users can find products by name, category, and price range.

    Precondition:
        ShopEasy API server is running. At least 20 products exist across multiple categories with varying price points. Search index is up to date.

    Pre-Test Steps:
        1. Load test parameters and validate testbed.
        2. Validate ShopEasy API connectivity.
        3. Validate product catalog availability.
        4. Validate order processing system.
    Run Steps:
        1. Send a GET request to /api/products/search?q=Bluetooth to perform a keyword search. Verify the resul
        2. Send a GET request to /api/products?category=Electronics&sort=price_asc to filter products by the El
        3. Send a GET request to /api/products?min_price=25.00&max_price=100.00 to filter products within a spe
        4. Combine multiple filters by sending a GET request to /api/products?category=Electronics&min_price=25
    Post-Test:
        Revert any settings changed during the test.
    """

    _skip_pre_testcase_dump_check = True

    name = "Regression : Regression: Product Search and Filtering"
    TESTCASE_ID = "TC-002"

    def __init__(self):
        super(TestTC_002, self).__init__()
        self._parameters = [
            Parameter(name="product_category", param_type="string", default="Electronics",
                      help="Default product category for test operations"),
            Parameter(name="customer_id", param_type="string", default="CUST-001",
                      help="Customer ID for order operations"),
        ]
        self._product_id = None
        self._product_ids = []
        self._category_id = None
        self._order_id = None
        self._order_ids = []

    def pre_testcase(self, testbed_obj):
        self.__dict__.update(self.params)
        ShopEaseBaseTestCase.pre_testcase(self, testbed_obj)

        LOGGER.info("Pre-Req: Validate product catalog availability")
        products = self.get_products_from_testbed(testbed_obj, product_count=1)
        LOGGER.info("Pass: Product catalog validated")

        LOGGER.info("Pre-Req: Validate order system readiness")
        LOGGER.info("Pass: Order system is ready")


    def run_test(self):
        self._step_count = 0

        # --- Step 1 ---
        LOGGER.info(f"Step {self.step_count}: Send a GET request to /api/products/search?q=Bluetooth to perform a keyword search. Verify the resul")
        results = ProductTask.search_products(system, query="Bluetooth")
        TestUtils.test_assert_true(len(results) > 0, "Search should return products")
        LOGGER.info("Search returned %d products", len(results))

        # --- Step 2 ---
        LOGGER.info(f"Step {self.step_count}: Send a GET request to /api/products?category=Electronics&sort=price_asc to filter products by the El")
        results = ProductTask.search_products(system, category=self.product_category, min_price=25.00, max_price=100.00)
        LOGGER.info("Combined filter returned %d results", len(results))

        # --- Step 3 ---
        LOGGER.info(f"Step {self.step_count}: Send a GET request to /api/products?min_price=25.00&max_price=100.00 to filter products within a spe")
        results = ProductTask.search_products(system, min_price=25.00, max_price=100.00)
        LOGGER.info("Price filter returned %d products", len(results))

        # --- Step 4 ---
        LOGGER.info(f"Step {self.step_count}: Combine multiple filters by sending a GET request to /api/products?category=Electronics&min_price=25")
        results = ProductTask.search_products(system, category=self.product_category, min_price=25.00, max_price=100.00)
        LOGGER.info("Combined filter returned %d results", len(results))


    def post_testcase(self):
        self._step_count = 0

        if self._category_id:
            try:
                LOGGER.info("Post-test: Deleting category %s", self._category_id)
                CategoryTask.delete_categories(system, category_id=self._category_id)
            except Exception as err:
                LOGGER.warning("Failed to delete category: %s", err)

