#!/usr/bin/env python -tt
# -*- coding: utf-8 -*-

################################################################################
# Auto-generated test for: TC-001 - Smoke: Create and Verify Product
# Generated by: AI-Powered Agentic Test Automation System
# Generated at: 2026-04-15T15:15:00.897907
################################################################################

from __future__ import unicode_literals, absolute_import

import logging
import pytest
from datetime import datetime

from shopease_framework.base.base_test_case import ShopEaseBaseTestCase, Parameter
from shopease_framework.base.utils import TestUtils
from shopease_framework.workflows.catalog_sync import CatalogSync
from shopease_framework.tasks.category_task import CategoryTask
from shopease_framework.tasks.inventory_task import InventoryTask
from shopease_framework.tasks.product_task import ProductTask
from shopease_framework.tasks.user_task import UserTask

LOGGER = logging.getLogger(__name__)


@pytest.mark.Smoke
class TestTC_001(ShopEaseBaseTestCase):
    """
    Smoke: Create and Verify Product

    Description:
        Verify that a new product can be created in the ShopEasy platform with all required attributes and is visible in the product catalog.

    Precondition:
        ShopEasy API server is running and accessible. Valid admin credentials are available.

    Pre-Test Steps:
        1. Load test parameters and validate testbed.
        2. Validate ShopEasy API connectivity.
        3. Validate product catalog availability.
    Run Steps:
        1. Send a POST request to /api/products with a JSON body containing name 'Wireless Bluetooth Headphones
        2. Send a GET request to /api/products/{product_id} using the product ID returned from the creation ste
        3. Send a GET request to /api/catalog?category=Electronics to retrieve the full product catalog filtere
        4. Send a PUT request to /api/products/{product_id} with an updated price of 69.99 and a new promotiona
        5. Send a GET request to /api/products/{product_id} again to verify the price update persisted. Compare
    Post-Test:
        Revert any settings changed during the test.
    """

    _skip_pre_testcase_dump_check = True

    name = "Smoke : Smoke: Create and Verify Product"
    TESTCASE_ID = "TC-001"

    def __init__(self):
        super(TestTC_001, self).__init__()
        self._parameters = [
            Parameter(name="product_category", param_type="string", default="Electronics",
                      help="Default product category for test operations"),
            Parameter(name="test_email", param_type="string", default="testuser@example.com",
                      help="Test user email address"),
            Parameter(name="warehouse_id", param_type="string", default="WH-001",
                      help="Warehouse ID for inventory operations"),
        ]
        self._product_id = None
        self._product_ids = []
        self._category_id = None

    def pre_testcase(self, testbed_obj):
        self.__dict__.update(self.params)
        ShopEaseBaseTestCase.pre_testcase(self, testbed_obj)

        LOGGER.info("Pre-Req: Validate product catalog availability")
        products = self.get_products_from_testbed(testbed_obj, product_count=1)
        LOGGER.info("Pass: Product catalog validated")


    def run_test(self):
        self._step_count = 0

        # --- Step 1 ---
        LOGGER.info(f"Step {self.step_count}: Send a POST request to /api/products with a JSON body containing name 'Wireless Bluetooth Headphones")
        product_data = DataGenerator.random_product(category=self.product_category)
        create_resp = ProductTask.create_product(system, product_data)
        TestUtils.test_assert_true(create_resp.get("result"), "Product creation should succeed")
        self._product_id = create_resp["product_id"]
        self._product_ids.append(self._product_id)
        LOGGER.info("Product created: ID=%s", self._product_id)

        # --- Step 2 ---
        LOGGER.info(f"Step {self.step_count}: Send a GET request to /api/products/{{product_id}} using the product ID returned from the creation ste")
        LOGGER.info("Executing: Send a GET request to /api/products/{{product_id}} using the product ID returned f")
        LOGGER.info("Expected: HTTP 200 response is returned. The product name is 'Wireless Bluetooth Headphone")
        product_info = ProductService.get_product_info(system)
        assert product_info.return_code == 200, f"ShopEasy API not reachable: HTTP {product_info.return_code}"
        LOGGER.info("ShopEasy API accessible - Version: %s",
                    product_info.data[0].get("Version", "N/A") if product_info.data else "N/A")

        # --- Step 3 ---
        LOGGER.info(f"Step {self.step_count}: Send a GET request to /api/catalog?category=Electronics to retrieve the full product catalog filtere")
        results = ProductTask.search_products(system, category=self.product_category)
        TestUtils.test_assert_true(len(results) > 0, "Category search should return results")
        LOGGER.info("Category filter returned %d products", len(results))

        # --- Step 4 ---
        LOGGER.info(f"Step {self.step_count}: Send a PUT request to /api/products/{{product_id}} with an updated price of 69.99 and a new promotiona")
        update_data = {"price": 69.99, "promo_tag": "Summer Sale"}
        update_resp = ProductTask.update_product(system, self._product_id, update_data)
        TestUtils.test_assert_true(update_resp.get("result"), "Product update should succeed")
        LOGGER.info("Product %s updated", self._product_id)

        # --- Step 5 ---
        LOGGER.info(f"Step {self.step_count}: Send a GET request to /api/products/{{product_id}} again to verify the price update persisted. Compare")
        LOGGER.info("Applying discount code SAVE10")
        LOGGER.info("Discount code applied successfully")


    def post_testcase(self):
        self._step_count = 0

        if self._category_id:
            try:
                LOGGER.info("Post-test: Deleting category %s", self._category_id)
                CategoryTask.delete_categories(system, category_id=self._category_id)
            except Exception as err:
                LOGGER.warning("Failed to delete category: %s", err)

