"""
Test Generator Agent - Uses AI/LLM to convert test case steps into executable Python test code.
Falls back to template-based generation if no LLM is configured.

When a reference test repository is configured (local path or GitHub), the agent
scans it for similar existing test files, available library modules, and common
import patterns.  This context is injected into:
  - The LLM prompt (so the model produces code that uses real project libraries)
  - The template generator (so fallback code mirrors real repo conventions)
"""

import os
import json
import re
import textwrap
from datetime import datetime

from agents.base_agent import BaseAgent
from agents.repo_context import RepoContext
from config import (
    LLM_PROVIDER, LLM_API_KEY, LLM_MODEL, LLM_BASE_URL,
    LLM_TEMPERATURE, LLM_MAX_TOKENS, GENERATED_TESTS_DIR,
)


# =============================================================================
# Template for standalone test framework (NO Atlas dependencies)
# =============================================================================

_TEMPLATE = '''\
#!/usr/bin/env python
# -*- coding: utf-8 -*-

################################################################################
# Auto-generated test for: {pid} - {name_short}
# Generated by: AI-Powered Agentic Test Automation System (Standalone Demo)
# Generated at: {timestamp}
################################################################################

import logging
import pytest
from datetime import datetime

# Standalone framework imports (NO Atlas dependencies)
import sys
import os
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from standalone_framework import BaseTestCase, MockAPIClient, assert_equals, assert_true, assert_contains

LOGGER = logging.getLogger(__name__)


@pytest.mark.{marker}
class Test{safe_pid}(BaseTestCase):
    """
    {name}

    Description:
        {description}

    Precondition:
        {precondition}

    Test Steps:
{run_steps_doc}
    """

    def __init__(self):
        super(Test{safe_pid}, self).__init__()
        self.api_client = MockAPIClient()
        self.test_data = {{
            "product_category": "{product_category}",
            "test_email": "{test_email}",
            "warehouse_id": "{warehouse_id}",
        }}
{init_instance_vars}

    def test_{safe_pid_lower}(self):
        """Test case: {name_short}"""
        # Initialize test
        self.setup_method()

{run_test_body}

        # Cleanup
        self.teardown_method()
'''


# =============================================================================
# Service -> import mapping (ShopEasy framework import lines)
# =============================================================================

_MODEL_IMPORTS = {
    "product":        "from shopease_framework.tasks.product_task import ProductTask",
    "category":       "from shopease_framework.tasks.category_task import CategoryTask",
    "order":          "from shopease_framework.tasks.order_task import OrderTask",
    "cart":           "from shopease_framework.tasks.cart_task import CartTask",
    "user":           "from shopease_framework.tasks.user_task import UserTask",
    "inventory":      "from shopease_framework.tasks.inventory_task import InventoryTask",
    "payment":        "from shopease_framework.tasks.payment_task import PaymentTask",
    "notification":   "from shopease_framework.tasks.notification_task import NotificationTask",
    "report":         "from shopease_framework.tasks.report_task import ReportTask",
    "product_service": "from shopease_framework.models.product_service import ProductService",
    "order_service":   "from shopease_framework.models.order_service import OrderService",
    "order_config":   "from shopease_framework.helpers.order_config import OrderConfig",
    "job_helper":     "from shopease_framework.helpers.job_helper import JobHelper",
    "data_generator": "from shopease_framework.helpers.data_generator import DataGenerator",
    "checkout":       "from shopease_framework.workflows.checkout_flow import CheckoutFlow",
    "catalog_sync":   "from shopease_framework.workflows.catalog_sync import CatalogSync",
}

_KEYWORD_IMPORT_MAP = {
    "product":      ["product"],
    "create product": ["product", "data_generator"],
    "catalog":      ["product", "category", "catalog_sync"],
    "category":     ["category"],
    "order":        ["order", "order_config"],
    "checkout":     ["cart", "order", "payment", "checkout"],
    "cart":         ["cart"],
    "shopping cart": ["cart"],
    "user":         ["user"],
    "register":     ["user"],
    "auth":         ["user"],
    "login":        ["user"],
    "inventory":    ["inventory", "job_helper"],
    "stock":        ["inventory"],
    "warehouse":    ["inventory", "job_helper", "catalog_sync"],
    "payment":      ["payment", "order"],
    "refund":       ["payment", "order"],
    "notification": ["notification"],
    "alert":        ["notification"],
    "report":       ["report"],
    "export":       ["report"],
    "shipping":     ["order"],
    "search":       ["product"],
    "filter":       ["product"],
    "discount":     ["cart", "order"],
    "sync":         ["inventory", "catalog_sync", "job_helper"],
}


class TestGeneratorAgent(BaseAgent):
    """
    Agent that generates executable Python test code from test case steps.
    Uses LLM when available, falls back to template-based generation.
    Leverages a reference test repository for context-aware generation.
    """

    def __init__(self):
        super().__init__("TestGeneratorAgent")
        self._llm_available = bool(LLM_API_KEY)
        self._repo_ctx = RepoContext()
        if self._repo_ctx.available:
            n_tests = len(self._repo_ctx.get_test_files())
            n_libs = len(self._repo_ctx.get_library_modules())
            self.log_event("init", f"Reference repo loaded: {n_tests} test files, {n_libs} library modules")
        else:
            self.log_event("init", "No reference repo configured (REFERENCE_REPO_LOCAL_PATH)")
        if self._llm_available:
            self.log_event("init", f"TestGeneratorAgent initialized with LLM: {LLM_PROVIDER}/{LLM_MODEL}")
        else:
            self.log_event("init", "TestGeneratorAgent initialized (template mode - no LLM_API_KEY set)")

    def generate_test(self, test_case_data):
        """Generate an executable Python test file from a parsed test case."""
        self.start_timer()
        pid = test_case_data.get("pid", "unknown")
        self.log_event("generate_start", f"Generating test for {pid}")

        os.makedirs(GENERATED_TESTS_DIR, exist_ok=True)

        repo_ctx = self._repo_ctx.build_generation_context(test_case_data)
        if repo_ctx["repo_available"]:
            n_sim = len(repo_ctx["similar_tests"])
            self.log_event("repo_context", f"Found {n_sim} similar test(s) in reference repo")

        if self._llm_available:
            code = self._generate_with_llm(test_case_data, repo_ctx)
            method = "llm"
        else:
            code = self._generate_with_template(test_case_data, repo_ctx)
            method = "template"

        safe_pid = re.sub(r'[^a-zA-Z0-9_]', '_', pid)
        filename = f"test_{safe_pid}.py"
        file_path = os.path.join(GENERATED_TESTS_DIR, filename)

        with open(file_path, "w", encoding="utf-8") as f:
            f.write(code)

        self.log_event("generate_complete",
                        f"Generated test for {pid} via {method}: {filename}",
                        {"file_path": file_path, "method": method,
                         "lines": code.count('\n') + 1,
                         "repo_context_used": repo_ctx["repo_available"],
                         "elapsed_s": self.elapsed_seconds()})

        return {
            "file_path": file_path,
            "code": code,
            "method": method,
            "test_case_id": pid,
            "repo_context_used": repo_ctx["repo_available"],
        }

    def regenerate_test(self, test_case_data, previous_code, error_info):
        """Regenerate test code after a failure, incorporating error context."""
        self.start_timer()
        pid = test_case_data.get("pid", "unknown")
        self.log_event("regenerate_start", f"Regenerating test for {pid} after failure")

        if self._llm_available:
            code = self._regenerate_with_llm(test_case_data, previous_code, error_info)
            method = "llm_fix"
        else:
            code = self._regenerate_with_template(test_case_data, previous_code, error_info)
            method = "template_fix"

        safe_pid = re.sub(r'[^a-zA-Z0-9_]', '_', pid)
        filename = f"test_{safe_pid}.py"
        file_path = os.path.join(GENERATED_TESTS_DIR, filename)

        with open(file_path, "w", encoding="utf-8") as f:
            f.write(code)

        self.log_event("regenerate_complete",
                        f"Regenerated test for {pid} via {method}: {filename}",
                        {"file_path": file_path, "method": method,
                         "elapsed_s": self.elapsed_seconds()})

        return {"file_path": file_path, "code": code, "method": method, "test_case_id": pid}

    # =========================================================================
    # LLM-based generation
    # =========================================================================

    def _generate_with_llm(self, test_case_data, repo_ctx=None):
        prompt = self._build_generation_prompt(test_case_data, repo_ctx)
        response = self._call_llm(prompt)
        return self._extract_code_from_response(response)

    def _regenerate_with_llm(self, test_case_data, previous_code, error_info):
        prompt = self._build_fix_prompt(test_case_data, previous_code, error_info)
        response = self._call_llm(prompt)
        return self._extract_code_from_response(response)

    def _build_generation_prompt(self, tc, repo_ctx=None):
        steps_text = ""
        for step in tc.get("steps", []):
            steps_text += f"\nStep {step['step_number']}:\n"
            steps_text += f"  Description: {step['description']}\n"
            steps_text += f"  Expected Result: {step['expected_result']}\n"

        ref_context_block = ""
        if repo_ctx and repo_ctx.get("repo_available"):
            ref_context_block += "\n\n===== REFERENCE REPOSITORY CONTEXT =====\n"
            if repo_ctx.get("common_imports"):
                ref_context_block += "\nCOMMON IMPORTS:\n"
                for imp in repo_ctx["common_imports"][:15]:
                    ref_context_block += f"  {imp}\n"
            if repo_ctx.get("library_summary"):
                ref_context_block += f"\nAVAILABLE LIBRARY MODULES:\n{repo_ctx['library_summary'][:2000]}\n"
            if repo_ctx.get("similar_tests"):
                ref_context_block += "\nSIMILAR EXISTING TESTS:\n"
                for sim in repo_ctx["similar_tests"]:
                    ref_context_block += f"\n--- {sim['file']} (similarity: {sim['score']}) ---\n"
                    ref_context_block += sim["code"][:3000] + "\n"

        return f"""You are a test automation engineer for ShopEasy E-Commerce Platform.
Generate a Python test script using the shopease_framework.

TEST CASE: {tc.get('pid', '')} - {tc.get('name', '')}
DESCRIPTION: {tc.get('description', '')}
PRECONDITION: {tc.get('precondition', '')}

TEST STEPS:
{steps_text}
{ref_context_block}

CRITICAL RULES:
1. Use `super(ClassName, self).__init__()` (explicit class name)
2. Call `self.__dict__.update(self.params)` as FIRST line in pre_testcase
3. Call `ShopEaseBaseTestCase.pre_testcase(self, testbed_obj)` in pre_testcase
4. `run_test(self)` takes NO testbed_obj argument
5. Use `self.api_system` for all API calls
6. Use `LOGGER.info(f"Step {{self.step_count}}: ...")` for each step
7. Use `TestUtils.test_assert_equals(expected, actual, message)` for validation

Generate ONLY the Python code, no explanations."""

    def _build_fix_prompt(self, tc, previous_code, error_info):
        return f"""Fix this failed test script.

TEST CASE: {tc.get('pid', '')} - {tc.get('name', '')}

PREVIOUS CODE:
```python
{previous_code}
```

ERROR:
{error_info.get('error_type', 'N/A')}: {error_info.get('error_message', 'N/A')}
Traceback:
{error_info.get('traceback', 'N/A')}

Generate ONLY the fixed Python code."""

    def _call_llm(self, prompt):
        try:
            if LLM_PROVIDER == "openai":
                return self._call_openai(prompt)
            elif LLM_PROVIDER == "azure":
                return self._call_azure(prompt)
            else:
                self.log_event("llm_error", f"Unknown LLM provider: {LLM_PROVIDER}")
                return ""
        except Exception as e:
            self.log_event("llm_error", f"LLM call failed: {e}")
            return ""

    def _call_openai(self, prompt):
        import openai
        client = openai.OpenAI(api_key=LLM_API_KEY, base_url=LLM_BASE_URL or None)
        response = client.chat.completions.create(
            model=LLM_MODEL,
            messages=[
                {"role": "system", "content": "You are an expert test automation engineer."},
                {"role": "user", "content": prompt},
            ],
            temperature=LLM_TEMPERATURE, max_tokens=LLM_MAX_TOKENS,
        )
        return response.choices[0].message.content

    def _call_azure(self, prompt):
        import openai
        client = openai.AzureOpenAI(
            api_key=LLM_API_KEY, azure_endpoint=LLM_BASE_URL, api_version="2024-02-01",
        )
        response = client.chat.completions.create(
            model=LLM_MODEL,
            messages=[
                {"role": "system", "content": "You are an expert test automation engineer."},
                {"role": "user", "content": prompt},
            ],
            temperature=LLM_TEMPERATURE, max_tokens=LLM_MAX_TOKENS,
        )
        return response.choices[0].message.content

    def _extract_code_from_response(self, response):
        if not response:
            return self._generate_with_template({})
        pattern = r'```(?:python)?\s*\n(.*?)```'
        matches = re.findall(pattern, response, re.DOTALL)
        if matches:
            return matches[0].strip()
        return response.strip()

    # =========================================================================
    # Template-based generation (fallback when no LLM)
    # =========================================================================

    def _generate_with_template(self, tc, repo_ctx=None):
        pid = tc.get("pid", "UNKNOWN")
        safe_pid = re.sub(r'[^a-zA-Z0-9_]', '_', pid)
        safe_pid_lower = safe_pid.lower()
        name = tc.get("name", "Unnamed Test Case")
        name_short = name[:120]
        description = tc.get("description", "N/A")
        precondition = tc.get("precondition", "N/A")
        steps = tc.get("steps", [])

        marker = self._detect_marker(name)
        init_instance_vars = self._build_init_vars(steps)
        run_test_body = self._build_run_test_standalone(steps)
        run_steps_doc = self._build_run_steps_doc(steps)

        # Default test parameters
        product_category = "Electronics"
        test_email = "testuser@example.com"
        warehouse_id = "WH-001"

        return _TEMPLATE.format(
            pid=pid, safe_pid=safe_pid, safe_pid_lower=safe_pid_lower,
            name=name, name_short=name_short,
            description=description[:500], precondition=precondition[:500],
            timestamp=datetime.now().isoformat(), marker=marker,
            init_instance_vars=init_instance_vars,
            run_test_body=run_test_body,
            run_steps_doc=run_steps_doc,
            product_category=product_category,
            test_email=test_email,
            warehouse_id=warehouse_id,
        )

    def _detect_marker(self, name):
        name_lower = name.lower()
        if "comprehensive" in name_lower:
            return "Comprehensive"
        elif "regression" in name_lower:
            return "Regression"
        elif "smoke" in name_lower:
            return "Smoke"
        elif "integration" in name_lower:
            return "Integration"
        return "Comprehensive"

    def _collect_imports(self, steps):
        all_text = " ".join(
            s.get("description", "") + " " + s.get("expected_result", "")
            for s in steps
        ).lower()

        needed_keys = set()
        for keyword, import_keys in _KEYWORD_IMPORT_MAP.items():
            if keyword in all_text:
                needed_keys.update(import_keys)
        needed_keys.add("product")

        lines = []
        seen = set()
        for key in sorted(needed_keys):
            imp = _MODEL_IMPORTS.get(key)
            if imp:
                for line in imp.split("\n"):
                    if line and line not in seen:
                        lines.append(line)
                        seen.add(line)
        return "\n".join(lines)

    def _build_parameters(self, steps):
        all_text = " ".join(
            s.get("description", "") + " " + s.get("expected_result", "")
            for s in steps
        ).lower()
        params = []
        if any(kw in all_text for kw in ["product", "catalog", "sku"]):
            params.append(
                '            Parameter(name="product_category", param_type="string", '
                'default="Electronics",\n'
                '                      help="Default product category for test operations"),')
        if any(kw in all_text for kw in ["order", "checkout", "payment"]):
            params.append(
                '            Parameter(name="customer_id", param_type="string", '
                'default="CUST-001",\n'
                '                      help="Customer ID for order operations"),')
        if any(kw in all_text for kw in ["user", "register", "auth", "login"]):
            params.append(
                '            Parameter(name="test_email", param_type="string", '
                'default="testuser@example.com",\n'
                '                      help="Test user email address"),')
        if any(kw in all_text for kw in ["inventory", "stock", "warehouse"]):
            params.append(
                '            Parameter(name="warehouse_id", param_type="string", '
                'default="WH-001",\n'
                '                      help="Warehouse ID for inventory operations"),')
        if not params:
            params.append('            # No additional parameters required for this test case')
        return "\n".join(params)

    def _build_init_vars(self, steps):
        all_text = " ".join(
            s.get("description", "") + " " + s.get("expected_result", "")
            for s in steps
        ).lower()
        lines = []
        if any(kw in all_text for kw in ["product", "create", "catalog"]):
            lines.extend(["        self._product_id = None", "        self._product_ids = []"])
        if "category" in all_text:
            lines.append("        self._category_id = None")
        if any(kw in all_text for kw in ["order", "checkout"]):
            lines.extend(["        self._order_id = None", "        self._order_ids = []"])
        if any(kw in all_text for kw in ["cart", "shopping"]):
            lines.append("        self._cart_id = None")
        if any(kw in all_text for kw in ["user", "register"]):
            lines.append("        self._user_id = None")
        if any(kw in all_text for kw in ["payment", "transaction"]):
            lines.append("        self._transaction_id = None")
        if any(kw in all_text for kw in ["notification", "rule"]):
            lines.append("        self._rule_created = False")
        if not lines:
            lines.append("        self._test_data = {}")
        lines.append("")
        return "\n".join(lines)

    def _build_pre_testcase(self, steps):
        all_text = " ".join(
            s.get("description", "") + " " + s.get("expected_result", "")
            for s in steps
        ).lower()
        lines = []
        if any(kw in all_text for kw in ["product", "catalog", "inventory"]):
            lines.extend([
                '        LOGGER.info("Pre-Req: Validate product catalog availability")',
                '        products = self.get_products_from_testbed(testbed_obj, product_count=1)',
                '        LOGGER.info("Pass: Product catalog validated")',
                '',
            ])
        if any(kw in all_text for kw in ["order", "checkout", "cart"]):
            lines.extend([
                '        LOGGER.info("Pre-Req: Validate order system readiness")',
                '        LOGGER.info("Pass: Order system is ready")',
                '',
            ])
        if not lines:
            lines.append('        LOGGER.info("Pre-test: ShopEasy API system validated")')
            lines.append('')
        return "\n".join(lines) + "\n"

    def _build_run_test_standalone(self, steps):
        """Build test body using standalone framework with mock API."""
        body_lines = []
        for step in steps:
            sn = step["step_number"]
            desc = step.get("description", "").strip()
            expected = step.get("expected_result", "").strip()
            desc_short = desc[:100].replace('\n', ' ')
            body_lines.append(f"        # --- Step {sn} ---")
            body_lines.append(
                f'        self.log_step("{self._escape_fstring(desc_short)}")')
            impl = self._generate_step_impl_standalone(sn, desc, expected)
            body_lines.extend(impl)
            body_lines.append("")
        return "\n".join(body_lines) + "\n"

    def _generate_step_impl_standalone(self, step_num, description, expected_result):
        """Generate step implementation using mock API client."""
        desc_lower = description.lower()
        lines = []

        if "create" in desc_lower and "product" in desc_lower and "search" not in desc_lower:
            lines.extend(self._gen_create_product_standalone(description))
        elif "search" in desc_lower or "filter" in desc_lower or "catalog" in desc_lower:
            lines.extend(self._gen_search_products_standalone(description))
        elif "update" in desc_lower and "product" in desc_lower:
            lines.extend(self._gen_update_product_standalone(description))
        elif "get" in desc_lower and "product" in desc_lower:
            lines.extend(self._gen_verify_product_standalone(description))
        elif "create" in desc_lower and "category" in desc_lower:
            lines.extend(self._gen_create_category_standalone(description))
        elif "delete" in desc_lower and "category" in desc_lower:
            lines.extend(self._gen_delete_category_standalone(description))
        elif "create" in desc_lower and "cart" in desc_lower:
            lines.extend(self._gen_create_cart_standalone(description))
        elif "add" in desc_lower and "cart" in desc_lower:
            lines.extend(self._gen_add_to_cart_standalone(description))
        elif "checkout" in desc_lower or "order" in desc_lower:
            lines.extend(self._gen_checkout_standalone(description))
        elif "register" in desc_lower:
            lines.extend(self._gen_user_register_standalone(description))
        elif "login" in desc_lower:
            lines.extend(self._gen_user_login_standalone(description))
        elif "update" in desc_lower and "profile" in desc_lower:
            lines.extend(self._gen_update_profile_standalone(description))
        else:
            # Generic step implementation
            lines.append('        # Step implementation')
            lines.append('        LOGGER.info("Executing step...")')
            lines.append('        assert True, "Step completed successfully"')

        return lines

    def _build_run_test(self, steps):
        body_lines = []
        for step in steps:
            sn = step["step_number"]
            desc = step.get("description", "").strip()
            expected = step.get("expected_result", "").strip()
            desc_short = desc[:100].replace('\n', ' ')
            body_lines.append(f"        # --- Step {sn} ---")
            body_lines.append(
                f'        LOGGER.info(f"Step {{self.step_count}}: {self._escape_fstring(desc_short)}")')
            impl = self._generate_step_impl(sn, desc, expected)
            body_lines.extend(impl)
            body_lines.append("")
        return "\n".join(body_lines) + "\n"

    def _generate_step_impl(self, step_num, description, expected_result):
        desc_lower = description.lower()
        combined = desc_lower + " " + expected_result.lower()
        lines = []

        if re.search(r"(post|create).*product", desc_lower) and "search" not in desc_lower:
            return self._gen_create_product(description)
        if re.search(r"search|filter|query.*product", desc_lower) or \
           re.search(r"get.*catalog|get.*products\?", desc_lower):
            return self._gen_search_products(description)
        if re.search(r"(put|update).*product", desc_lower):
            return self._gen_update_product(description)
        if re.search(r"get.*product.*detail|verify.*product", desc_lower) and "search" not in desc_lower:
            return self._gen_verify_product(description)
        if re.search(r"(post|create).*categor", desc_lower):
            return self._gen_create_category(description)
        if re.search(r"(add|associate).*product.*categor|categor.*product", desc_lower):
            return self._gen_category_products(description)
        if re.search(r"(put|update|rename).*categor", desc_lower):
            return self._gen_update_category(description)
        if re.search(r"delete.*categor", desc_lower):
            return self._gen_delete_category(description)
        if re.search(r"(post|create).*cart", desc_lower):
            return self._gen_create_cart(description)
        if re.search(r"add.*(item|product).*cart", desc_lower):
            return self._gen_add_to_cart(description)
        if re.search(r"(delete|remove).*(item|product).*cart", desc_lower):
            return self._gen_remove_from_cart(description)
        if re.search(r"(put|update).*cart.*item|quantity", desc_lower) and "remove" not in desc_lower:
            return self._gen_update_cart(description)
        if re.search(r"get.*cart|retrieve.*cart|verify.*cart", desc_lower):
            return self._gen_verify_cart(description)
        if re.search(r"checkout|place.*order", desc_lower):
            return self._gen_checkout(description)
        if re.search(r"(post|create).*order", desc_lower) and "checkout" not in desc_lower:
            return self._gen_create_order(description)
        if re.search(r"(put|update).*order.*status", desc_lower):
            return self._gen_update_order_status(description, expected_result)
        if re.search(r"tracking", desc_lower):
            return self._gen_tracking(description)
        if re.search(r"get.*order|retrieve.*order|verify.*order|fetch.*order", desc_lower):
            return self._gen_verify_order(description)
        if re.search(r"order.*history|customer.*orders", desc_lower):
            return self._gen_order_history(description)
        if re.search(r"register|sign.?up", desc_lower):
            return self._gen_user_register(description)
        if re.search(r"login|auth.*login|auth.*token", desc_lower):
            return self._gen_user_login(description)
        if re.search(r"(put|update).*profile", desc_lower):
            return self._gen_update_profile(description)
        if re.search(r"get.*profile|verify.*profile", desc_lower):
            return self._gen_verify_profile(description)
        if re.search(r"(get|check).*inventory|stock.*level", desc_lower):
            return self._gen_check_inventory(description)
        if re.search(r"adjust.*inventory|update.*inventory|add.*stock|subtract.*stock|reduce.*stock", desc_lower):
            return self._gen_adjust_inventory(description, expected_result)
        if re.search(r"sync.*inventory|sync.*warehouse|trigger.*sync", desc_lower):
            return self._gen_sync_inventory(description)
        if re.search(r"poll|wait.*job|check.*job", desc_lower):
            return self._gen_poll_job(description)
        if re.search(r"process.*payment|charge|authorize", desc_lower):
            return self._gen_process_payment(description)
        if re.search(r"(get|verify).*payment|transaction.*detail", desc_lower):
            return self._gen_verify_payment(description)
        if re.search(r"refund", desc_lower):
            return self._gen_refund(description)
        if re.search(r"(post|create).*notification.*rule|create.*rule", desc_lower):
            return self._gen_create_notification_rule(description)
        if re.search(r"verify.*notification|notification.*log|delivery.*status", desc_lower):
            return self._gen_verify_notification(description)
        if re.search(r"(put|modify|update).*rule", desc_lower):
            return self._gen_modify_notification_rule(description)
        if re.search(r"delete.*rule|remove.*rule", desc_lower):
            return self._gen_delete_notification_rule(description)
        if re.search(r"discount|coupon|promo", desc_lower):
            return self._gen_apply_discount(description)
        if re.search(r"verification.*email|email.*verif", desc_lower):
            return self._gen_verify_email(description)
        if re.search(r"report|export", desc_lower):
            return self._gen_report_ops(description)
        return self._gen_generic_step(description, expected_result)

    # =========================================================================
    # Step implementation generators
    # =========================================================================

    def _gen_create_product(self, desc):
        return [
            '        product_data = DataGenerator.random_product(category=self.product_category)',
            '        create_resp = ProductTask.create_product(system, product_data)',
            '        TestUtils.test_assert_true(create_resp.get("result"), "Product creation should succeed")',
            '        self._product_id = create_resp["product_id"]',
            '        self._product_ids.append(self._product_id)',
            '        LOGGER.info("Product created: ID=%s", self._product_id)',
        ]

    def _gen_search_products(self, desc):
        dl = desc.lower()
        if "category" in dl and "price" in dl:
            return [
                '        results = ProductTask.search_products(system, category=self.product_category, min_price=25.00, max_price=100.00)',
                '        LOGGER.info("Combined filter returned %d results", len(results))',
            ]
        elif "category" in dl:
            return [
                '        results = ProductTask.search_products(system, category=self.product_category)',
                '        TestUtils.test_assert_true(len(results) > 0, "Category search should return results")',
                '        LOGGER.info("Category filter returned %d products", len(results))',
            ]
        elif "price" in dl:
            return [
                '        results = ProductTask.search_products(system, min_price=25.00, max_price=100.00)',
                '        LOGGER.info("Price filter returned %d products", len(results))',
            ]
        return [
            '        results = ProductTask.search_products(system, query="Bluetooth")',
            '        TestUtils.test_assert_true(len(results) > 0, "Search should return products")',
            '        LOGGER.info("Search returned %d products", len(results))',
        ]

    def _gen_update_product(self, desc):
        return [
            '        update_data = {"price": 69.99, "promo_tag": "Summer Sale"}',
            '        update_resp = ProductTask.update_product(system, self._product_id, update_data)',
            '        TestUtils.test_assert_true(update_resp.get("result"), "Product update should succeed")',
            '        LOGGER.info("Product %s updated", self._product_id)',
        ]

    def _gen_verify_product(self, desc):
        return [
            '        details = ProductTask.get_product_details(system, self._product_id)',
            '        TestUtils.test_assert_true(details is not None, "Product details should be retrievable")',
            '        LOGGER.info("Product %s verified: %s", self._product_id, details.get("name"))',
        ]

    def _gen_create_category(self, desc):
        return [
            '        category_name = TestUtils.generate_unique_name("category")',
            '        create_resp = CategoryTask.create_category(system, category_name)',
            '        TestUtils.test_assert_true(create_resp.get("result"), "Category creation should succeed")',
            '        self._category_id = create_resp["category_id"]',
            '        LOGGER.info("Category created: ID=%s, Name=%s", self._category_id, category_name)',
        ]

    def _gen_category_products(self, desc):
        return [
            '        assoc_result = CategoryTask.add_verify_products_in_category(',
            '            system, [self._category_id], self._product_ids or [1001, 1002, 1003])',
            '        TestUtils.test_assert_true(assoc_result, "Product-category association should succeed")',
            '        LOGGER.info("Products associated with category %s", self._category_id)',
        ]

    def _gen_update_category(self, desc):
        return [
            '        all_cats = CategoryTask.get_all_categories(system)',
            '        TestUtils.test_assert_true(len(all_cats) > 0, "Should have at least one category")',
            '        LOGGER.info("Categories verified: %d total", len(all_cats))',
        ]

    def _gen_delete_category(self, desc):
        return [
            '        del_result = CategoryTask.delete_categories(system, category_id=self._category_id)',
            '        TestUtils.test_assert_true(del_result, "Category deletion should succeed")',
            '        self._category_id = None',
            '        LOGGER.info("Category deleted successfully")',
        ]

    def _gen_create_cart(self, desc):
        return [
            '        cart_resp = CartTask.create_cart(system, self.customer_id)',
            '        TestUtils.test_assert_true(cart_resp.get("result"), "Cart creation should succeed")',
            '        self._cart_id = cart_resp["cart_id"]',
            '        LOGGER.info("Cart created: %s", self._cart_id)',
        ]

    def _gen_add_to_cart(self, desc):
        return [
            '        add_resp = CartTask.add_item_to_cart(system, self._cart_id, "P-101", quantity=2)',
            '        TestUtils.test_assert_true(add_resp.get("result"), "Item addition to cart should succeed")',
            '        LOGGER.info("Item added to cart %s", self._cart_id)',
        ]

    def _gen_remove_from_cart(self, desc):
        return [
            '        remove_result = CartTask.remove_item_from_cart(system, self._cart_id, "P-101")',
            '        TestUtils.test_assert_true(remove_result, "Item removal from cart should succeed")',
            '        LOGGER.info("Item removed from cart %s", self._cart_id)',
        ]

    def _gen_update_cart(self, desc):
        return [
            '        cart_details = CartTask.get_cart_details(system, self._cart_id)',
            '        LOGGER.info("Cart updated: %d items", len(cart_details.get("items", [])))',
        ]

    def _gen_verify_cart(self, desc):
        return [
            '        cart = CartTask.get_cart_details(system, self._cart_id)',
            '        LOGGER.info("Cart %s: total=%.2f, items=%d",',
            '                    self._cart_id, cart.get("total", 0), len(cart.get("items", [])))',
        ]

    def _gen_checkout(self, desc):
        return [
            '        checkout_resp = CartTask.checkout_cart(system, self._cart_id, payment_method="credit_card")',
            '        TestUtils.test_assert_true(checkout_resp.get("result"), "Checkout should succeed")',
            '        self._order_id = checkout_resp.get("order_id")',
            '        LOGGER.info("Checkout complete: order %s", self._order_id)',
        ]

    def _gen_create_order(self, desc):
        return [
            '        config = OrderConfig("standard")',
            '        config.add_item("P-101", quantity=2, price=29.99)',
            '        config.add_item("P-102", quantity=1, price=49.99)',
            '        config.set_payment("credit_card")',
            '        order_resp = OrderTask.create_order(system, config.generate_order_payload())',
            '        TestUtils.test_assert_true(order_resp.get("result"), "Order creation should succeed")',
            '        self._order_id = order_resp["order_id"]',
            '        LOGGER.info("Order created: %s", self._order_id)',
        ]

    def _gen_update_order_status(self, desc, expected):
        dl = desc.lower()
        if "shipped" in dl:
            ns = "shipped"
        elif "delivered" in dl:
            ns = "delivered"
        elif "cancelled" in dl:
            ns = "cancelled"
        else:
            ns = "processing"
        return [
            f'        status_resp = OrderTask.update_order_status(system, self._order_id, "{ns}")',
            f'        TestUtils.test_assert_true(status_resp.get("result"), "Status update to {ns} should succeed")',
            f'        LOGGER.info("Order %s status updated to {ns}", self._order_id)',
        ]

    def _gen_tracking(self, desc):
        return [
            '        tracking_events = ["picked_up", "in_transit", "out_for_delivery"]',
            '        for event in tracking_events:',
            '            LOGGER.info("  Tracking event: %s", event)',
            '        LOGGER.info("All tracking events recorded for order %s", self._order_id)',
        ]

    def _gen_verify_order(self, desc):
        return [
            '        order_status = OrderTask.get_order_status(system, self._order_id)',
            '        TestUtils.test_assert_true(order_status is not None, "Order status should be retrievable")',
            '        LOGGER.info("Order %s status: %s", self._order_id, order_status.get("status"))',
        ]

    def _gen_order_history(self, desc):
        return [
            '        history = OrderTask.get_order_history(system, customer_id=self.customer_id)',
            '        TestUtils.test_assert_true(len(history) > 0, "Customer order history should not be empty")',
            '        LOGGER.info("Order history: %d orders found", len(history))',
        ]

    def _gen_user_register(self, desc):
        return [
            '        user_data = DataGenerator.random_user()',
            '        reg_resp = UserTask.create_user(system, user_data)',
            '        TestUtils.test_assert_true(reg_resp.get("result"), "User registration should succeed")',
            '        self._user_id = reg_resp["user_id"]',
            '        LOGGER.info("User registered: ID=%s", self._user_id)',
        ]

    def _gen_user_login(self, desc):
        return [
            '        auth_resp = UserTask.authenticate_user(system, self.test_email, "TestPass123!")',
            '        TestUtils.test_assert_true(auth_resp.get("result"), "Authentication should succeed")',
            '        TestUtils.test_assert_true("token" in auth_resp, "Auth response should contain a token")',
            '        LOGGER.info("User authenticated successfully")',
        ]

    def _gen_update_profile(self, desc):
        return [
            '        profile_update = {"display_name": "TestUser", "phone": "+1-555-0123"}',
            '        update_resp = UserTask.update_user(system, self._user_id, profile_update)',
            '        TestUtils.test_assert_true(update_resp.get("result"), "Profile update should succeed")',
            '        LOGGER.info("User profile updated")',
        ]

    def _gen_verify_profile(self, desc):
        return [
            '        user = UserTask.get_user_details(system, self._user_id)',
            '        TestUtils.test_assert_true(user is not None, "User details should be retrievable")',
            '        LOGGER.info("User profile verified: %s", user.get("email"))',
        ]

    def _gen_check_inventory(self, desc):
        return [
            '        inventory = InventoryTask.check_inventory(system, "P-201")',
            '        TestUtils.test_assert_equals("in_stock", inventory.get("status"), "Product should be in stock")',
            '        LOGGER.info("Inventory: %d units", inventory.get("quantity", 0))',
        ]

    def _gen_adjust_inventory(self, desc, expected):
        if "subtract" in desc.lower() or "reduce" in desc.lower():
            return [
                '        adj_resp = InventoryTask.update_inventory(system, "P-201", 7, operation="set")',
                '        TestUtils.test_assert_true(adj_resp.get("result"), "Inventory reduction should succeed")',
                '        low_stock = InventoryTask.get_low_stock_products(system, threshold=10)',
                '        LOGGER.info("Stock reduced, low-stock alert check complete")',
            ]
        return [
            '        adj_resp = InventoryTask.update_inventory(system, "P-201", 75, operation="add")',
            '        TestUtils.test_assert_true(adj_resp.get("result"), "Inventory adjustment should succeed")',
            '        LOGGER.info("Inventory adjusted: new quantity = %s", adj_resp.get("new_quantity"))',
        ]

    def _gen_sync_inventory(self, desc):
        return [
            '        sync_resp = InventoryTask.sync_warehouse_inventory(system, self.warehouse_id)',
            '        TestUtils.test_assert_true(sync_resp.get("result"), "Warehouse sync should succeed")',
            '        LOGGER.info("Warehouse sync initiated: job_id=%s", sync_resp.get("job_id"))',
        ]

    def _gen_poll_job(self, desc):
        return [
            '        job_done = JobHelper.check_job_status(system, "SYNC-001", expected_status="completed")',
            '        TestUtils.test_assert_true(job_done, "Sync job should complete")',
            '        LOGGER.info("Sync job completed successfully")',
        ]

    def _gen_process_payment(self, desc):
        return [
            '        payment_data = {"method": "credit_card", "card_token": "tok_visa_success", "amount": 149.97, "currency": "USD"}',
            '        pay_resp = PaymentTask.process_payment(system, self._order_id, payment_data)',
            '        TestUtils.test_assert_true(pay_resp.get("result"), "Payment should be approved")',
            '        self._transaction_id = pay_resp["transaction_id"]',
            '        LOGGER.info("Payment processed: txn=%s", self._transaction_id)',
        ]

    def _gen_verify_payment(self, desc):
        return [
            '        txn = PaymentTask.verify_payment(system, self._transaction_id)',
            '        TestUtils.test_assert_equals("approved", txn.get("status"), "Transaction should be approved")',
            '        LOGGER.info("Payment verified: %s (amount=%.2f)", self._transaction_id, txn.get("amount", 0))',
        ]

    def _gen_refund(self, desc):
        return [
            '        refund_resp = PaymentTask.process_refund_payment(system, self._transaction_id, amount=50.00)',
            '        TestUtils.test_assert_true(refund_resp.get("result"), "Partial refund should succeed")',
            '        LOGGER.info("Refund processed: %s", refund_resp.get("refund_id"))',
        ]

    def _gen_create_notification_rule(self, desc):
        return [
            '        rule_data = {"event_type": "order.placed", "channel": "email",',
            '                     "recipients": ["ops-team@shopeasy.com"], "severity": "info"}',
            '        success, rule_resp = NotificationTask.create_notification_rule(system, rule_data, event_types=["order.placed"])',
            '        TestUtils.test_assert_true(success, "Notification rule creation should succeed")',
            '        self._rule_created = True',
            '        LOGGER.info("Notification rule created")',
        ]

    def _gen_verify_notification(self, desc):
        return [
            '        notif_sent = NotificationTask.verify_notification_sent(system, "order.placed")',
            '        TestUtils.test_assert_true(notif_sent, "Notification should be sent")',
            '        LOGGER.info("Notification delivery verified")',
        ]

    def _gen_modify_notification_rule(self, desc):
        return [
            '        rules = NotificationTask.get_notification_rules(system)',
            '        TestUtils.test_assert_true(len(rules) > 0, "Should have notification rules")',
            '        LOGGER.info("Notification rules: %d active", len(rules))',
        ]

    def _gen_delete_notification_rule(self, desc):
        return [
            '        del_result = NotificationTask.delete_notification_rules(system)',
            '        TestUtils.test_assert_true(del_result, "Rule deletion should succeed")',
            '        self._rule_created = False',
            '        LOGGER.info("Notification rules deleted")',
        ]

    def _gen_apply_discount(self, desc):
        return [
            '        LOGGER.info("Applying discount code SAVE10")',
            '        LOGGER.info("Discount code applied successfully")',
        ]

    def _gen_verify_email(self, desc):
        return [
            '        LOGGER.info("Verifying email notification was sent")',
            '        LOGGER.info("Email verification confirmed")',
        ]

    def _gen_report_ops(self, desc):
        if "run" in desc.lower() or "execute" in desc.lower():
            return [
                '        run_result = ReportTask.run_report(system)',
                '        TestUtils.test_assert_true(run_result.get("result"), "Report execution should succeed")',
                '        LOGGER.info("Report executed: %s", run_result.get("report_id"))',
            ]
        return [
            '        reports = ReportTask.get_all_reports(system)',
            '        LOGGER.info("Available reports: %d", len(reports))',
        ]

    def _gen_generic_step(self, desc, expected):
        desc_short = desc[:200].replace('\n', ' ').replace('"', '\\"')
        expected_short = expected[:200].replace('\n', ' ').replace('"', '\\"') if expected else ""
        lines = [f'        LOGGER.info("Executing: {self._escape_fstring(desc_short[:80])}")']
        if expected_short:
            lines.append(f'        LOGGER.info("Expected: {self._escape_fstring(expected_short[:80])}")')
        lines.extend([
            '        product_info = ProductService.get_product_info(system)',
            '        assert product_info.return_code == 200, f"ShopEasy API not reachable: HTTP {product_info.return_code}"',
            '        LOGGER.info("ShopEasy API accessible - Version: %s",',
            '                    product_info.data[0].get("Version", "N/A") if product_info.data else "N/A")',
        ])
        return lines

    def _build_post_testcase(self, steps):
        all_text = " ".join(
            s.get("description", "") + " " + s.get("expected_result", "") for s in steps
        ).lower()
        lines = ['        self._step_count = 0']
        if "category" in all_text:
            lines.extend([
                '', '        if self._category_id:',
                '            try:',
                '                LOGGER.info("Post-test: Deleting category %s", self._category_id)',
                '                CategoryTask.delete_categories(system, category_id=self._category_id)',
                '            except Exception as err:',
                '                LOGGER.warning("Failed to delete category: %s", err)',
            ])
        if any(kw in all_text for kw in ["notification", "rule"]):
            lines.extend([
                '', '        if self._rule_created:',
                '            try:',
                '                NotificationTask.delete_notification_rules(system)',
                '            except Exception as err:',
                '                LOGGER.warning("Failed to delete rules: %s", err)',
            ])
        if "cart" in all_text:
            lines.extend([
                '', '        if self._cart_id:',
                '            try:',
                '                CartTask.clear_cart(system, self._cart_id)',
                '            except Exception as err:',
                '                LOGGER.warning("Failed to clear cart: %s", err)',
            ])
        if any(kw in all_text for kw in ["user", "register"]):
            lines.extend([
                '', '        if self._user_id:',
                '            try:',
                '                UserTask.delete_user(system, self._user_id)',
                '            except Exception as err:',
                '                LOGGER.warning("Failed to delete user: %s", err)',
            ])
        if not any(kw in all_text for kw in ["category", "notification", "rule", "cart", "user", "register"]):
            lines.extend(['', '        LOGGER.info("Post-test cleanup complete.")'])
        lines.append('')
        return "\n".join(lines) + "\n"

    def _build_pre_steps_doc(self, steps):
        lines = ["        1. Load test parameters and validate testbed.",
                  "        2. Validate ShopEasy API connectivity."]
        all_text = " ".join(s.get("description", "") for s in steps).lower()
        n = 3
        if any(kw in all_text for kw in ["product", "catalog"]):
            lines.append(f"        {n}. Validate product catalog availability.")
            n += 1
        if any(kw in all_text for kw in ["order", "payment"]):
            lines.append(f"        {n}. Validate order processing system.")
        return "\n".join(lines)

    def _build_run_steps_doc(self, steps):
        return "\n".join(
            f"        {s['step_number']}. {s['description'][:100].replace(chr(10), ' ')}"
            for s in steps
        )

    @staticmethod
    def _escape_fstring(text):
        return text.replace("{", "{{").replace("}", "}}").replace('"', '\\"')

    def _regenerate_with_template(self, tc, previous_code, error_info):
        traceback_text = error_info.get("traceback", "")
        code = previous_code
        if "ModuleNotFoundError" in traceback_text or "ImportError" in traceback_text:
            m = re.search(r"No module named '(\w+)'", traceback_text)
            if m:
                code = f"import {m.group(1)}\n" + code
        if "SSLError" in traceback_text and "urllib3.disable_warnings" not in code:
            code = "import urllib3\nurllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)\n" + code
        if code == previous_code:
            self.log_event("regenerate_fallback", "No specific fix found, regenerating from template")
            repo_ctx = self._repo_ctx.build_generation_context(tc)
            code = self._generate_with_template(tc, repo_ctx)
        return code


# =============================================================================
# Standalone Framework Implementation Methods
# =============================================================================

def _gen_create_product_standalone(description):
    """Generate product creation code using mock API."""
    return [
        '        product_data = {',
        '            "name": "Wireless Bluetooth Headphones",',
        '            "price": 79.99,',
        '            "category": self.test_data["product_category"],',
        '            "sku": "WBH-1001"',
        '        }',
        '        response = self.api_client.create_product(product_data)',
        '        assert_equals(201, response["status_code"], "Product creation should return 201")',
        '        self._product_id = response["product"]["id"]',
        '        LOGGER.info(f"Product created with ID: {self._product_id}")',
    ]


def _gen_search_products_standalone(description):
    """Generate product search code using mock API."""
    return [
        '        response = self.api_client.search_products(category=self.test_data["product_category"])',
        '        assert_equals(200, response["status_code"], "Search should return 200")',
        '        assert_greater(len(response["products"]), 0, "Search should return results")',
        '        LOGGER.info(f"Found {len(response[\'products\'])} products in category")',
    ]


def _gen_update_product_standalone(description):
    """Generate product update code using mock API."""
    return [
        '        update_data = {"price": 69.99, "promo_tag": "Summer Sale"}',
        '        response = self.api_client.update_product(self._product_id, update_data)',
        '        assert_equals(200, response["status_code"], "Product update should return 200")',
        '        LOGGER.info("Product updated successfully")',
    ]


    def _gen_verify_product_standalone(self, description):
        """Generate product verification code using mock API."""
        return [
            '        response = self.api_client.get_product(self._product_id)',
            '        assert_equals(200, response["status_code"], "Product retrieval should return 200")',
            '        product = response["product"]',
            '        LOGGER.info(f"Product verified: {product[\'name\']}")',
        ]

    def _gen_create_category_standalone(self, description):
        """Generate category creation code using mock API."""
        return [
            '        category_data = {',
            '            "name": "Summer Collection",',
            '            "description": "Seasonal summer products",',
            '            "display_order": 5,',
            '        }',
            '        response = self.api_client.create_category(category_data)',
            '        assert_equals(201, response["status_code"], "Category creation should return 201")',
            '        self._category_id = response["category"]["id"]',
            '        LOGGER.info(f"Category created with ID: {self._category_id}")',
        ]

    def _gen_delete_category_standalone(self, description):
        """Generate category deletion code using mock API."""
        return [
            '        response = self.api_client.delete_category(self._category_id, reassign_to="uncategorized")',
            '        assert_equals(204, response["status_code"], "Category deletion should return 204")',
            '        LOGGER.info("Category deleted successfully")',
        ]

    def _gen_create_cart_standalone(self, description):
    """Generate cart creation code using mock API."""
    return [
        '        response = self.api_client.create_cart(user_id="test-user-001")',
        '        assert_equals(201, response["status_code"], "Cart creation should return 201")',
        '        self._cart_id = response["cart"]["id"]',
        '        LOGGER.info(f"Cart created with ID: {self._cart_id}")',
    ]


def _gen_add_to_cart_standalone(description):
    """Generate add to cart code using mock API."""
    return [
        '        response = self.api_client.add_cart_item(self._cart_id, product_id=1001, quantity=2)',
        '        assert_equals(200, response["status_code"], "Add item should return 200")',
        '        LOGGER.info("Item added to cart")',
    ]


def _gen_checkout_standalone(description):
    """Generate checkout code using mock API."""
    return [
        '        order_data = {',
        '            "items": [{"product_id": 1001, "quantity": 2}],',
        '            "total": 159.98,',
        '            "customer_id": "test-user-001",',
        '            "shipping_address": {"street": "123 Test St", "city": "Test City"}',
        '        }',
        '        response = self.api_client.create_order(order_data)',
        '        assert_equals(201, response["status_code"], "Order creation should return 201")',
        '        self._order_id = response["order"]["id"]',
        '        LOGGER.info(f"Order created with ID: {self._order_id}")',
    ]


def _gen_user_register_standalone(description):
    """Generate user registration code using mock API."""
    return [
        '        user_data = {',
        '            "email": self.test_data["test_email"],',
        '            "first_name": "Jane",',
        '            "last_name": "Smith"',
        '        }',
        '        response = self.api_client.register_user(user_data)',
        '        assert_equals(201, response["status_code"], "User registration should return 201")',
        '        self._user_id = response["user"]["id"]',
        '        LOGGER.info(f"User registered with ID: {self._user_id}")',
    ]


def _gen_user_login_standalone(description):
    """Generate user login code using mock API."""
    return [
        '        # Mock login - in real system would authenticate',
        '        LOGGER.info("User authentication successful")',
        '        self.auth_token = "mock-jwt-token-12345"',
    ]


def _gen_update_profile_standalone(description):
    """Generate profile update code using mock API."""
    return [
        '        profile_data = {',
        '            "display_name": "JaneS",',
        '            "phone": "+1-555-0123",',
        '            "preferred_currency": "USD"',
        '        }',
        '        response = self.api_client.update_user_profile(self._user_id, profile_data)',
        '        assert_equals(200, response["status_code"], "Profile update should return 200")',
        '        LOGGER.info("Profile updated successfully")',
    ]


# Add the standalone methods to the TestGeneratorAgent class
TestGeneratorAgent._gen_create_product_standalone = _gen_create_product_standalone
TestGeneratorAgent._gen_search_products_standalone = _gen_search_products_standalone
TestGeneratorAgent._gen_update_product_standalone = _gen_update_product_standalone
TestGeneratorAgent._gen_verify_product_standalone = _gen_verify_product_standalone
TestGeneratorAgent._gen_create_category_standalone = _gen_create_category_standalone
TestGeneratorAgent._gen_delete_category_standalone = _gen_delete_category_standalone
TestGeneratorAgent._gen_create_cart_standalone = _gen_create_cart_standalone
TestGeneratorAgent._gen_add_to_cart_standalone = _gen_add_to_cart_standalone
TestGeneratorAgent._gen_checkout_standalone = _gen_checkout_standalone
TestGeneratorAgent._gen_user_register_standalone = _gen_user_register_standalone
TestGeneratorAgent._gen_user_login_standalone = _gen_user_login_standalone
TestGeneratorAgent._gen_update_profile_standalone = _gen_update_profile_standalone
