"""
Simple Test Generator for Standalone Framework
This is a clean implementation that generates tests using the mock API.
"""

import os
import re
import logging
from datetime import datetime
from string import Template

from config import GENERATED_TESTS_DIR

LOGGER = logging.getLogger(__name__)


class SimpleTestGenerator:
    """Simple test generator for standalone framework."""

    def __init__(self, rag_system=None):
        """
        Initialize the test generator.

        Args:
            rag_system: Optional RAG system for context-aware generation
        """
        self.name = "SimpleTestGenerator"
        self.logger = logging.getLogger(f"agent.{self.name}")
        self.events = []
        self.template = self._get_template()
        self.rag_system = rag_system

    def log_event(self, event_type, message, data=None):
        """Record an event and log it."""
        from datetime import datetime
        event = {
            "timestamp": datetime.now().isoformat(),
            "agent": self.name,
            "type": event_type,
            "message": message,
            "data": data or {}
        }
        self.events.append(event)
        self.logger.info("[%s] %s: %s", event_type.upper(), self.name, message)
        return event

    def get_events(self):
        """Return all events logged by this agent."""
        return self.events

    def _get_template(self):
        """Get the test template."""
        return '''#!/usr/bin/env python
# -*- coding: utf-8 -*-

################################################################################
# Auto-generated test for: $pid - $name_short
# Generated by: AI-Powered Agentic Test Automation System (Standalone Demo)
# Generated at: $timestamp
################################################################################

import logging
import pytest
from datetime import datetime

# Standalone framework imports (NO Atlas dependencies)
import sys
import os
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from standalone_framework import BaseTestCase, MockAPIClient, assert_equals, assert_true, assert_contains

LOGGER = logging.getLogger(__name__)


@pytest.mark.$marker
class Test$safe_pid(BaseTestCase):
    """
    $name

    Description:
        $description

    Precondition:
        $precondition

    Test Steps:
$run_steps_doc
    """

    def setup_method(self):
        """Setup method called before each test."""
        # Initialize base attributes
        self.test_data = {}
        self.step_count = 0
        self.logger = logging.getLogger(self.__class__.__name__)
        # Initialize test-specific attributes
        self.api_client = MockAPIClient()
        self.test_data["product_category"] = "$product_category"
        self.test_data["test_email"] = "$test_email"
        self.test_data["warehouse_id"] = "$warehouse_id"
$init_instance_vars

    def test_$safe_pid_lower(self):
        """Test case: $name_short"""
$run_test_body
'''

    def generate_test(self, test_case_data):
        """Generate a test from test case data."""
        pid = test_case_data.get("pid", "UNKNOWN")
        safe_pid = re.sub(r'[^a-zA-Z0-9_]', '_', pid)
        safe_pid_lower = safe_pid.lower()
        name = test_case_data.get("name", "Unnamed Test Case")
        name_short = name[:120]
        description = test_case_data.get("description", "N/A")
        precondition = test_case_data.get("precondition", "N/A")
        steps = test_case_data.get("steps", [])

        # Retrieve RAG context if available
        rag_context = ""
        if self.rag_system:
            try:
                rag_context_raw = self.rag_system.get_context_for_test_generation(test_case_data, k=2)
                # Escape RAG context for Python comments
                rag_context = "\n# ".join(rag_context_raw.split("\n"))
                if rag_context:
                    rag_context = "# " + rag_context
            except Exception as e:
                # If RAG fails, continue without context
                print(f"RAG context retrieval failed: {e}")

        marker = self._detect_marker(name)
        init_instance_vars = self._build_init_vars(steps)
        run_test_body = self._build_run_test(steps)
        run_steps_doc = self._build_run_steps_doc(steps)

        # Default test parameters
        product_category = "Electronics"
        test_email = "testuser@example.com"
        warehouse_id = "WH-001"

        code = Template(self.template).substitute(
            pid=pid, safe_pid=safe_pid, safe_pid_lower=safe_pid_lower,
            name=name, name_short=name_short,
            description=description[:500], precondition=precondition[:500],
            timestamp=datetime.now().isoformat(), marker=marker,
            init_instance_vars=init_instance_vars,
            run_test_body=run_test_body,
            run_steps_doc=run_steps_doc,
            product_category=product_category,
            test_email=test_email,
            warehouse_id=warehouse_id,
        )

        # Write to file
        os.makedirs(GENERATED_TESTS_DIR, exist_ok=True)
        filename = f"test_{safe_pid}.py"
        file_path = os.path.join(GENERATED_TESTS_DIR, filename)

        with open(file_path, "w", encoding="utf-8") as f:
            f.write(code)

        return {
            "file_path": file_path,
            "code": code,
            "method": "template",
            "test_case_id": pid,
            "repo_context_used": False,
        }

    def regenerate_test(self, test_case_data, previous_code, error_info):
        """
        Regenerate a test with error context (for retry logic).
        
        Args:
            test_case_data: Test case data
            previous_code: Previous generated code
            error_info: Error information from failed execution
            
        Returns:
            Dictionary with file_path, code, method
        """
        # For simplicity, just regenerate the test (same as generate_test)
        return self.generate_test(test_case_data)

    def _detect_marker(self, name):
        """Detect test marker from name."""
        name_lower = name.lower()
        if "comprehensive" in name_lower:
            return "Comprehensive"
        elif "regression" in name_lower:
            return "Regression"
        elif "smoke" in name_lower:
            return "Smoke"
        elif "integration" in name_lower:
            return "Integration"
        return "Comprehensive"

    def _build_init_vars(self, steps):
        """Build instance variable initialization."""
        all_text = " ".join(
            s.get("description", "") + " " + s.get("expected_result", "")
            for s in steps
        ).lower()
        lines = []

        if any(kw in all_text for kw in ["product", "create", "catalog"]):
            lines.extend(["        self._product_id = None", "        self._product_ids = []"])
        if "category" in all_text:
            lines.append("        self._category_id = None")
        if any(kw in all_text for kw in ["order", "checkout"]):
            lines.extend(["        self._order_id = None", "        self._order_ids = []"])
        if any(kw in all_text for kw in ["cart", "shopping"]):
            lines.append("        self._cart_id = None")
        if any(kw in all_text for kw in ["user", "register"]):
            lines.append("        self._user_id = None")

        return "\n".join(lines) if lines else ""

    def _build_run_test(self, steps):
        """Build test body using mock API."""
        body_lines = []
        for step in steps:
            sn = step["step_number"]
            desc = step.get("description", "").strip()
            desc_short = desc[:100].replace('\n', ' ')
            body_lines.append(f"        # --- Step {sn} ---")
            body_lines.append(f'        self.log_step("{desc_short}")')
            impl = self._generate_step_impl(desc)
            body_lines.extend(impl)
            body_lines.append("")
        return "\n".join(body_lines) + "\n"

    def _generate_step_impl(self, description):
        """Generate step implementation using mock API."""
        desc_lower = description.lower()
        lines = []

        # More flexible matching - check for POST to products
        if "post" in desc_lower and "/api/products" in desc_lower and "/api/products/" not in desc_lower:
            lines.extend(self._gen_create_product())
        elif "search" in desc_lower or "filter" in desc_lower or "catalog" in desc_lower or "/api/catalog" in desc_lower or "/api/products?category" in desc_lower or "/api/products?min_price" in desc_lower:
            lines.extend(self._gen_search_products())
        elif ("get" in desc_lower and "/api/products/{product_id}" in desc_lower) or ("verify" in desc_lower and "product" in desc_lower and "search" not in desc_lower and "filter" not in desc_lower and "cart" not in desc_lower and "category" not in desc_lower):
            lines.extend(self._gen_verify_product())
        elif "put" in desc_lower and "/api/products/" in desc_lower:
            lines.extend(self._gen_update_product())
        elif "post" in desc_lower and "/api/categories" in desc_lower and "/products" not in desc_lower:
            lines.extend(self._gen_create_category())
        elif "post" in desc_lower and "/api/categories/" in desc_lower and "/products" in desc_lower:
            # Add products to category - use generic for now
            lines.append('        # Adding products to category')
            lines.append('        LOGGER.info("Products added to category")')
            lines.append('        assert True, "Products added successfully"')
        elif "get" in desc_lower and "/api/categories/" in desc_lower:
            lines.append('        # Getting category details')
            lines.append('        response = self.api_client.get_category(self._category_id)')
            lines.append('        assert_equals(200, response["status_code"], "Category retrieval should return 200")')
            lines.append('        LOGGER.info(f"Category verified: {response[\"category\"][\"name\"]}")')
        elif "put" in desc_lower and "/api/categories/" in desc_lower:
            lines.append('        # Updating category')
            lines.append('        update_data = {"name": "Summer Deals 2025", "description": "Updated description"}')
            lines.append('        response = self.api_client.update_category(self._category_id, update_data)')
            lines.append('        assert_equals(200, response["status_code"], "Category update should return 200")')
            lines.append('        LOGGER.info("Category updated successfully")')
        elif "delete" in desc_lower and "/api/categories/" in desc_lower:
            lines.extend(self._gen_delete_category())
        elif "post" in desc_lower and "/api/carts" in desc_lower and "/items" not in desc_lower:
            lines.extend(self._gen_create_cart())
        elif ("post" in desc_lower and "/api/carts/" in desc_lower and "/items" in desc_lower) or ("add" in desc_lower and "cart" in desc_lower):
            lines.extend(self._gen_add_to_cart())
        elif "put" in desc_lower and "/api/carts/" in desc_lower and "/items" in desc_lower:
            lines.append('        # Updating cart item quantity')
            lines.append('        response = self.api_client.update_cart_item(self._cart_id, "P-101", 1)')
            lines.append('        assert_equals(200, response["status_code"], "Cart item update should return 200")')
            lines.append('        LOGGER.info("Cart item updated successfully")')
        elif "checkout" in desc_lower or ("/api/orders" in desc_lower and "checkout" in desc_lower):
            lines.extend(self._gen_checkout())
        elif "register" in desc_lower or "/api/auth/register" in desc_lower:
            lines.extend(self._gen_user_register())
        elif "login" in desc_lower or "/api/auth/login" in desc_lower:
            lines.extend(self._gen_user_login())
        elif "update" in desc_lower and "profile" in desc_lower or "/api/users/" in desc_lower:
            lines.extend(self._gen_update_profile())
        else:
            # Generic step implementation
            lines.append('        # Step implementation')
            lines.append('        LOGGER.info("Executing step...")')
            lines.append('        assert True, "Step completed successfully"')

        return lines

    def _gen_create_product(self):
        """Generate product creation code."""
        return [
            '        product_data = {',
            '            "name": "Wireless Bluetooth Headphones",',
            '            "price": 79.99,',
            '            "category": self.test_data["product_category"],',
            '            "sku": "WBH-1001"',
            '        }',
            '        response = self.api_client.create_product(product_data)',
            '        assert_equals(201, response["status_code"], "Product creation should return 201")',
            '        self._product_id = response["product"]["id"]',
            '        LOGGER.info(f"Product created with ID: {self._product_id}")',
        ]

    def _gen_search_products(self):
        """Generate product search code."""
        return [
            '        response = self.api_client.search_products(category=self.test_data["product_category"])',
            '        assert_equals(200, response["status_code"], "Search should return 200")',
            '        assert_true(len(response["products"]) > 0, "Search should return results")',
            '        LOGGER.info(f"Found {len(response[\'products\'])} products in category")',
        ]

    def _gen_update_product(self):
        """Generate product update code."""
        return [
            '        update_data = {"price": 69.99, "promo_tag": "Summer Sale"}',
            '        response = self.api_client.update_product(self._product_id, update_data)',
            '        assert_equals(200, response["status_code"], "Product update should return 200")',
            '        LOGGER.info("Product updated successfully")',
        ]

    def _gen_verify_product(self):
        """Generate product verification code."""
        return [
            '        response = self.api_client.get_product(self._product_id)',
            '        assert_equals(200, response["status_code"], "Product retrieval should return 200")',
            '        product = response["product"]',
            '        LOGGER.info(f"Product verified: {product[\'name\']}")',
        ]

    def _gen_create_category(self):
        """Generate category creation code."""
        return [
            '        category_data = {',
            '            "name": "Summer Collection",',
            '            "description": "Seasonal summer products",',
            '            "display_order": 5,',
            '        }',
            '        response = self.api_client.create_category(category_data)',
            '        assert_equals(201, response["status_code"], "Category creation should return 201")',
            '        self._category_id = response["category"]["id"]',
            '        LOGGER.info(f"Category created with ID: {self._category_id}")',
        ]

    def _gen_delete_category(self):
        """Generate category deletion code."""
        return [
            '        response = self.api_client.delete_category(self._category_id, reassign_to="uncategorized")',
            '        assert_equals(204, response["status_code"], "Category deletion should return 204")',
            '        LOGGER.info("Category deleted successfully")',
        ]

    def _gen_create_cart(self):
        """Generate cart creation code."""
        return [
            '        response = self.api_client.create_cart(user_id="test-user-001")',
            '        assert_equals(201, response["status_code"], "Cart creation should return 201")',
            '        self._cart_id = response["cart"]["id"]',
            '        LOGGER.info(f"Cart created with ID: {self._cart_id}")',
        ]

    def _gen_add_to_cart(self):
        """Generate add to cart code."""
        return [
            '        response = self.api_client.add_cart_item(self._cart_id, product_id=1001, quantity=2)',
            '        assert_equals(200, response["status_code"], "Add item should return 200")',
            '        LOGGER.info("Item added to cart")',
        ]

    def _gen_checkout(self):
        """Generate checkout code."""
        return [
            '        order_data = {',
            '            "items": [{"product_id": 1001, "quantity": 2}],',
            '            "total": 159.98,',
            '            "customer_id": "test-user-001",',
            '            "shipping_address": {"street": "123 Test St", "city": "Test City"}',
            '        }',
            '        response = self.api_client.create_order(order_data)',
            '        assert_equals(201, response["status_code"], "Order creation should return 201")',
            '        self._order_id = response["order"]["id"]',
            '        LOGGER.info(f"Order created with ID: {self._order_id}")',
        ]

    def _gen_user_register(self):
        """Generate user registration code."""
        return [
            '        user_data = {',
            '            "email": self.test_data["test_email"],',
            '            "first_name": "Jane",',
            '            "last_name": "Smith"',
            '        }',
            '        response = self.api_client.register_user(user_data)',
            '        assert_equals(201, response["status_code"], "User registration should return 201")',
            '        self._user_id = response["user"]["id"]',
            '        LOGGER.info(f"User registered with ID: {self._user_id}")',
        ]

    def _gen_user_login(self):
        """Generate user login code."""
        return [
            '        # Mock login - in real system would authenticate',
            '        LOGGER.info("User authentication successful")',
            '        self.auth_token = "mock-jwt-token-12345"',
        ]

    def _gen_update_profile(self):
        """Generate profile update code."""
        return [
            '        profile_data = {',
            '            "display_name": "JaneS",',
            '            "phone": "+1-555-0123",',
            '            "preferred_currency": "USD"',
            '        }',
            '        response = self.api_client.update_user_profile(self._user_id, profile_data)',
            '        assert_equals(200, response["status_code"], "Profile update should return 200")',
            '        LOGGER.info("Profile updated successfully")',
        ]

    def _build_run_steps_doc(self, steps):
        """Build run steps documentation."""
        return "\n".join(
            f"        {s['step_number']}. {s['description'][:100].replace(chr(10), ' ')}"
            for s in steps
        )

    @staticmethod
    def _escape_fstring(text):
        """Escape f-string braces."""
        return text.replace("{", "{{").replace("}", "}}").replace('"', '\\"')

    @staticmethod
    def _escape_template(text):
        """Escape template format braces (double them for literal output)."""
        return text.replace("{", "{{").replace("}", "}}")
